"""Classification curriculum — 20 topics with full educational content."""

from learning import QuizQuestion, Topic

TOPICS = [
    Topic(id="clf_01", title="What is Classification?", section="classification", order=1, difficulty="beginner",
        objectives=["Define classification", "Identify classification problems", "Distinguish from regression"],
        concept="Classification is supervised learning where the model predicts a discrete class label. Given input features, the model assigns each observation to one of a predefined set of categories.",
        why_matters="Classification is one of the most common ML tasks: spam detection, disease diagnosis, image recognition, credit scoring, customer churn prediction.",
        simple_explanation="Classification answers: 'Which category does this belong to?' Spam or not spam? Cat or dog? Approved or denied?",
        example="Email spam detection: Input = email text and metadata. Output = 'spam' or 'not spam'. The model learns patterns (e.g., 'free money', suspicious links) that distinguish spam from legitimate emails.",
        python_example="```python\nfrom sklearn.linear_model import LogisticRegression\n\nmodel = LogisticRegression()\nmodel.fit(X_train, y_train)  # y contains class labels (0 or 1)\npredictions = model.predict(X_test)  # predicted class labels\n```",
        practice_exercise="Load a dataset with labels (e.g., Titanic). 1. What is the target? 2. How many classes? 3. Is it binary or multiclass? 4. What features are available?",
        quiz=[QuizQuestion(question="Which is a classification problem?", options=["Predicting house price", "Predicting if an email is spam", "Predicting temperature", "Predicting stock price"], correct_index=1, explanation="Spam detection predicts a category (spam/not spam). The others predict continuous values — regression problems.")],
        common_mistakes=["Treating a classification target as continuous", "Using accuracy for imbalanced datasets", "Not understanding what the model actually predicts"],
        takeaways=["Classification predicts discrete labels", "Common: binary (2 classes) and multiclass (3+ classes)", "Different evaluation metrics than regression"],
        lab_module="classification",
    ),
    Topic(id="clf_02", title="Classification vs Regression", section="classification", order=2, difficulty="beginner",
        objectives=["Distinguish classification from regression", "Identify problem types correctly", "Handle borderline cases"],
        concept="Classification predicts categories (spam/not spam, species A/B/C). Regression predicts numbers (price, temperature). The target variable determines the problem type.",
        why_matters="Choosing the wrong problem type leads to nonsensical results. You cannot average class labels, and predicting a category number (1,2,3) as continuous is meaningless.",
        simple_explanation="Classification: 'Will it rain today?' (yes/no). Regression: 'How much rain will fall?' (mm).",
        example="Predicting exam scores (0-100) is regression. Predicting pass/fail is classification. Same input data, different target framing.",
        common_mistakes=["Using classification when regression is appropriate (loss of information)", "Using regression for ordinal classes", "Forcing binary when the problem is naturally multiclass"],
        practice_exercise="For each scenario, classify as classification or regression: 1. Predicting house prices. 2. Predicting if a customer will churn. 3. Predicting exam scores. 4. Predicting product quality grade (A/B/C).",
        quiz=[QuizQuestion(question="Predicting 'income bracket' (low/medium/high) is:", options=["Regression — income is numerical", "Classification — brackets are categories", "Both — depends on the algorithm", "Neither — it's clustering"], correct_index=1, explanation="Even though income is numerical, 'brackets' (low/medium/high) are categories. The target is discrete, making this classification.")],
        takeaways=["Classification → categories, Regression → numbers", "The target variable determines the problem type", "Same input data can be either, depending on the target"],
        lab_module="classification",
    ),
    Topic(id="clf_03", title="Binary Classification", section="classification", order=3, difficulty="beginner",
        objectives=["Handle two-class problems", "Understand positive/negative classes", "Apply binary classification metrics"],
        concept="Binary classification has exactly two classes: spam/not spam, malignant/benign, pass/fail. One class is 'positive' (the event of interest) and the other 'negative'.",
        why_matters="Binary classification is the simplest and most common form. Most healthcare diagnosis, fraud detection, and quality control problems are binary.",
        simple_explanation="Two outcomes. Yes or no. True or false. The model learns to tell them apart.",
        example="Disease diagnosis: positive = has disease, negative = healthy. The model examines features (age, blood pressure, test results) and predicts disease status.",
        common_mistakes=["Choosing the wrong 'positive' class", "Not considering class imbalance (99% negative, 1% positive)", "Reporting only accuracy on imbalanced data"],
        practice_exercise="Train a binary classifier on Titanic. 1. Which class is positive (survived)? 2. What is accuracy? 3. What is the class balance? 4. Is accuracy misleading?",
        quiz=[QuizQuestion(question="In disease screening, 'positive' means:", options=["The test result is good", "The patient has the disease", "The patient is healthy", "The test was successful"], correct_index=1, explanation="In medical contexts, 'positive' means the condition is present (has disease). This is why 'false positive' means incorrectly diagnosing a healthy person.")],
        takeaways=["Binary classification has two classes", "Define which class is 'positive' based on the problem", "Use precision, recall, F1 for imbalanced data"],
        lab_module="classification",
    ),
    Topic(id="clf_04", title="Multiclass Classification", section="classification", order=4, difficulty="beginner",
        objectives=["Handle three or more classes", "Understand one-vs-rest strategy", "Use multiclass-appropriate metrics"],
        concept="Multiclass has 3+ classes: species A/B/C, digits 0-9, sentiment positive/neutral/negative. Many binary classifiers extend via one-vs-rest (OvR) or one-vs-one (OvO).",
        why_matters="Many real-world problems are multiclass: image recognition, medical diagnosis (multiple diseases), language identification.",
        simple_explanation="More than two options. The model picks the most likely one from all available classes.",
        example="Iris dataset: predict species (setosa, versicolor, virginica). The model examines petal length, petal width and assigns the most likely species.",
        python_example="```python\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Multiclass works automatically\nmodel = RandomForestClassifier()\nmodel.fit(X_train, y_train)  # y has 3+ unique values\npredictions = model.predict(X_test)\nprint(f'Classes: {model.classes_}')\n```",
        common_mistakes=["Assuming binary classifiers can't handle multiclass (most can via OvR)", "Not checking class balance across all classes", "Using binary metrics without adapting for multiclass"],
        practice_exercise="Train a classifier on a 3+ class dataset. 1. Check class balance. 2. Which classes are hardest to predict? 3. Look at the per-class report.",
        quiz=[QuizQuestion(question="How does Logistic Regression handle multiclass problems?", options=["It can't — only works for binary", "One-vs-Rest: trains one model per class", "It automatically creates one model", "It uses neural networks"], correct_index=1, explanation="Logistic Regression extends to multiclass via One-vs-Rest: it trains one model per class, each distinguishing that class from all others. The class with the highest probability wins.")],
        takeaways=["Most classifiers handle multiclass automatically", "One-vs-rest trains one model per class", "Check class balance for each class"],
        lab_module="classification",
    ),
    Topic(id="clf_05", title="Logistic Regression", section="classification", order=5, difficulty="beginner",
        objectives=["Understand how logistic regression works", "Apply it to binary classification", "Interpret coefficients and probabilities"],
        concept="Despite its name, logistic regression is a classifier. It applies the sigmoid function to a linear combination of features, producing a probability between 0 and 1. If probability > 0.5, predict class 1.",
        why_matters="Logistic regression is the most interpretable classifier. It shows exactly how each feature affects the probability of the positive class. It's the standard baseline.",
        simple_explanation="It draws a line (or hyperplane) to separate classes. The sigmoid converts the line's output into a probability.",
        example="Titanic: Logistic regression finds that being female increases survival probability (positive coefficient), while being in 3rd class decreases it (negative coefficient).",
        python_example="```python\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\n\npipeline = Pipeline([\n    ('scaler', StandardScaler()),\n    ('model', LogisticRegression())\n])\npipeline.fit(X_train, y_train)\n\n# Probabilities\nprobs = pipeline.predict_proba(X_test)[:, 1]\n\n# Coefficients\nfor name, coef in zip(feature_names, pipeline.named_steps['model'].coef_[0]):\n    print(f'{name}: {coef:.3f}')\n```",
        common_mistakes=["Forgetting to scale features (coefficients are meaningless without scaling)", "Using for non-linear problems (linear decision boundary)", "Not adjusting the classification threshold"],
        practice_exercise="Fit Logistic Regression on Titanic. 1. Which features have the largest coefficients? 2. Are they positive or negative? 3. Do the coefficients make sense?",
        quiz=[QuizQuestion(question="Why is feature scaling important for Logistic Regression?", options=["It's required by sklearn", "Coefficients are on different scales — scaling makes them comparable", "It speeds up training", "It prevents overfitting"], correct_index=1, explanation="Without scaling, a feature with range 0-100000 (income) will have a tiny coefficient compared to a feature with range 0-1 (binary). Scaling makes coefficients directly comparable.")],
        takeaways=["Most interpretable classifier", "Requires feature scaling", "Produces probabilities, not just labels"],
        lab_module="classification",
    ),
    Topic(id="clf_06", title="K-Nearest Neighbors (KNN)", section="classification", order=6, difficulty="beginner",
        objectives=["Understand the KNN algorithm", "Choose appropriate k values", "Apply KNN with proper preprocessing"],
        concept="KNN classifies a new point by majority vote of its k nearest training examples. Distance is typically Euclidean. No training phase — all computation is at prediction time (lazy learner).",
        why_matters="KNN is intuitive and non-parametric (no assumptions about data distribution). It's excellent for understanding instance-based learning.",
        simple_explanation="To classify a new patient, look at the k most similar patients. If 7 of 10 nearest patients have diabetes, predict diabetes.",
        python_example="```python\nfrom sklearn.neighbors import KNeighborsClassifier\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\n\n# KNN requires scaling!\npipeline = Pipeline([\n    ('scaler', StandardScaler()),\n    ('model', KNeighborsClassifier(n_neighbors=5))\n])\npipeline.fit(X_train, y_train)\n```",
        common_mistakes=["Not scaling features (Euclidean distance is scale-sensitive)", "Using too small k (noisy) or too large k (loses local patterns)", "Using KNN on high-dimensional data (curse of dimensionality)"],
        practice_exercise="Train KNN with k in [1, 3, 5, 10, 50]. 1. Plot accuracy vs k. 2. What is the optimal k? 3. What happens at k=1 (overfitting) and k=50 (underfitting)?",
        quiz=[QuizQuestion(question="What happens when k=1 in KNN?", options=["The model is very smooth and generalises well", "The model perfectly memorises the training data — overfitting", "The model cannot make predictions", "The model is the fastest"], correct_index=1, explanation="With k=1, each point is classified by its single nearest neighbour. This creates a jagged decision boundary that perfectly fits training data but generalises poorly — classic overfitting.")],
        takeaways=["KNN needs scaling (distance-based)", "Choose k with cross-validation", "Slow on large datasets (computes distances at prediction time)"],
        lab_module="classification",
    ),
    Topic(id="clf_07", title="Decision Trees", section="classification", order=7, difficulty="beginner",
        objectives=["Understand tree-based splitting", "Interpret decision trees visually", "Recognise overfitting risk"],
        concept="Decision trees split data using feature thresholds. At each node, the algorithm chooses the feature and threshold that best separates classes (maximises information gain). Creates an interpretable flowchart.",
        why_matters="Decision trees are fully interpretable (you can visualise the entire decision process), handle mixed data types, and require no scaling. But they overfit easily.",
        simple_explanation="Like a flowchart: 'Is age > 30?' → yes → 'Is income > 50K?' → yes → 'Approved'.",
        python_example="```python\nfrom sklearn.tree import DecisionTreeClassifier, plot_tree\nimport matplotlib.pyplot as plt\n\nmodel = DecisionTreeClassifier(max_depth=3, random_state=42)\nmodel.fit(X_train, y_train)\n\nplt.figure(figsize=(15, 8))\nplot_tree(model, feature_names=feature_names, class_names=['No','Yes'],\n          filled=True, rounded=True)\nplt.show()\n```",
        common_mistakes=["Using unlimited depth (massive overfitting)", "Not pruning the tree", "Trusting feature importance on noisy data"],
        practice_exercise="Train a Decision Tree with max_depth in [1, 3, 5, 10, None]. 1. Plot accuracy vs depth. 2. At what depth does overfitting start? 3. Visualise the tree at depth 3.",
        quiz=[QuizQuestion(question="Why do Decision Trees overfit easily?", options=["They are too slow", "Unlimited depth creates a rule for every training example, including noise", "They require scaling", "They can't handle missing values"], correct_index=1, explanation="An unlimited-depth tree can create a path for every single training point, perfectly memorising the data (including noise). This creates a model that fails completely on new data.")],
        takeaways=["Fully interpretable — visualise with plot_tree", "Prone to overfitting — limit max_depth", "No scaling needed"],
        lab_module="classification",
    ),
    Topic(id="clf_08", title="Random Forest", section="classification", order=8, difficulty="beginner",
        objectives=["Understand ensemble learning", "Apply Random Forest", "Extract and interpret feature importance"],
        concept="Random Forest builds many decision trees on random subsets of data and features, then averages their predictions. Each tree sees a different 'view' — the ensemble reduces overfitting.",
        why_matters="Random Forest is the most reliable 'default' classifier. It rarely overfits, handles missing values, needs no scaling, and provides feature importance.",
        simple_explanation="Instead of one expert (one tree), ask 100 experts and take a majority vote. Collective wisdom beats individual judgment.",
        python_example="```python\nfrom sklearn.ensemble import RandomForestClassifier\n\nmodel = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)\nmodel.fit(X_train, y_train)\n\nimportance = pd.Series(model.feature_importances_, index=feature_names).sort_values(ascending=False)\nimportance.head(10).plot(kind='barh')\n```",
        common_mistakes=["Not tuning max_depth (trees may still overfit individually)", "Using too few trees (<50, unstable estimates)", "Trusting feature importance on highly correlated features"],
        practice_exercise="Train Random Forest with n_estimators in [10, 50, 100, 200]. 1. How does accuracy change? 2. What are the top 3 features? 3. How does it compare to a single Decision Tree?",
        quiz=[QuizQuestion(question="Why does Random Forest use random subsets of features at each split?", options=["To save memory", "To make trees decorrelated so the ensemble reduces variance", "To speed up training", "It's a default setting that doesn't matter"], correct_index=1, explanation="If all trees split on the same top feature, they'd be similar. Random feature subsets force diversity — different trees capture different patterns, making the ensemble more robust.")],
        takeaways=["Ensemble of many random trees", "Robust, rarely overfits, good default", "Provides feature importance"],
        lab_module="classification",
    ),
    Topic(id="clf_09", title="Naive Bayes", section="classification", order=9, difficulty="beginner",
        objectives=["Understand Bayes' theorem application", "Apply Naive Bayes", "Know when the naive assumption works"],
        concept="Naive Bayes applies Bayes' theorem with the 'naive' assumption that all features are independent given the class. Despite this unrealistic assumption, it works surprisingly well — especially for text.",
        why_matters="Naive Bayes is extremely fast, works well with small data, and is the standard baseline for text classification (spam filtering, sentiment analysis).",
        simple_explanation="It calculates the probability of each class given the features, assuming features don't interact. Quick, simple, often effective.",
        python_example="```python\nfrom sklearn.naive_bayes import GaussianNB, MultinomialNB\n\n# For continuous features\nmodel = GaussianNB()\nmodel.fit(X_train, y_train)\n\n# For text/count data\nmodel = MultinomialNB()\nmodel.fit(X_train_counts, y_train)\n```",
        common_mistakes=["Using GaussianNB on highly correlated features (assumption violated)", "Expecting state-of-the-art accuracy (it's a baseline)", "Not checking feature independence assumption"],
        practice_exercise="Train Naive Bayes on a dataset. 1. How fast is it? 2. How does accuracy compare to Logistic Regression? 3. When might Naive Bayes outperform other models?",
        quiz=[QuizQuestion(question="Why is Naive Bayes called 'naive'?", options=["It's a simple algorithm", "It assumes all features are independent given the class — an unrealistic assumption", "It was invented by a naive researcher", "It doesn't use probabilities"], correct_index=1, explanation="The 'naive' part is the independence assumption: it treats each feature as if it provides independent evidence for the class. In reality, features often correlate, but the algorithm still works well in practice.")],
        takeaways=["Fast and effective baseline", "Best for text classification", "'Naive' independence assumption rarely holds but works in practice"],
        lab_module="classification",
    ),
    Topic(id="clf_10", title="Support Vector Machines", section="classification", order=10, difficulty="intermediate",
        objectives=["Understand maximum margin concept", "Apply SVM with different kernels", "Tune C and gamma parameters"],
        concept="SVM finds the hyperplane that maximises the margin (distance) between classes. Support vectors are the closest points to the boundary. Kernels (linear, RBF, polynomial) handle non-linear boundaries.",
        why_matters="SVMs are effective in high-dimensional spaces and when features exceed samples. They were state-of-the-art before deep learning.",
        python_example="```python\nfrom sklearn.svm import SVC\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\n\n# SVM requires scaling!\npipeline = Pipeline([\n    ('scaler', StandardScaler()),\n    ('model', SVC(kernel='rbf', C=1.0, gamma='scale'))\n])\npipeline.fit(X_train, y_train)\n```",
        common_mistakes=["Not scaling features (critical for SVM)", "Using RBF kernel on very large datasets (slow)", "Not tuning C and gamma"],
        practice_exercise="Train SVM with linear and RBF kernels. 1. Which performs better? 2. Try different C values (0.01, 1, 100). 3. How does scaling affect SVM performance?",
        quiz=[QuizQuestion(question="What does the C parameter control in SVM?", options=["Number of features", "The trade-off between wide margin and training errors", "The kernel type", "The number of support vectors"], correct_index=1, explanation="C controls regularisation: high C → narrow margin, fewer training errors (risk overfitting). Low C → wide margin, more tolerance for misclassification (risk underfitting).")],
        takeaways=["Maximises margin between classes", "Requires scaling", "RBF kernel for non-linear, Linear for speed"],
        lab_module="classification",
    ),
    Topic(id="clf_11", title="Gradient Boosting", section="classification", order=11, difficulty="intermediate",
        objectives=["Understand sequential ensemble learning", "Apply Gradient Boosting", "Tune learning_rate and n_estimators"],
        concept="Gradient Boosting builds trees sequentially: each new tree corrects the errors of the previous ones. It's an additive model that gradually reduces bias. XGBoost, LightGBM are popular implementations.",
        why_matters="Gradient Boosting often achieves the highest accuracy on tabular data. It's the default choice in competitions and production systems.",
        simple_explanation="Each new tree focuses on the mistakes the previous trees made. Like reviewing only the questions you got wrong.",
        python_example="```python\nfrom sklearn.ensemble import GradientBoostingClassifier\n\nmodel = GradientBoostingClassifier(\n    n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42\n)\nmodel.fit(X_train, y_train)\n```",
        common_mistakes=["Too many estimators with high learning rate (overfitting)", "Not using early stopping", "Forgetting to limit max_depth (each tree should be simple)"],
        practice_exercise="Train Gradient Boosting with learning_rate in [0.01, 0.1, 0.3]. 1. How does learning_rate affect performance? 2. Try n_estimators in [50, 100, 200]. 3. What is the best combination?",
        quiz=[QuizQuestion(question="What is the relationship between learning_rate and n_estimators in Gradient Boosting?", options=["They are independent", "Lower learning_rate needs more trees but produces a better model", "Higher learning_rate is always better", "They must sum to 100"], correct_index=1, explanation="Lower learning_rate means each tree contributes less, so you need more trees. But slower learning typically produces a more robust model. Typical trade-off: lr=0.1 with 100 trees vs lr=0.01 with 1000 trees.")],
        takeaways=["Sequential ensemble — each tree fixes previous errors", "Often highest accuracy on tabular data", "learning_rate and n_estimators trade off"],
        lab_module="classification",
    ),
    Topic(id="clf_12", title="Model Parameters", section="classification", order=12, difficulty="beginner",
        objectives=["Distinguish parameters from hyperparameters", "Know key hyperparameters per algorithm", "Apply systematic tuning"],
        concept="Parameters are learned from data (e.g., logistic regression coefficients). Hyperparameters are set before training (k in KNN, max_depth in trees). Hyperparameter tuning finds the best settings via cross-validation.",
        why_matters="Default hyperparameters are rarely optimal. Proper tuning can improve accuracy by 2-5%, which matters in competitive and production settings.",
        simple_explanation="Parameters = what the model learns. Hyperparameters = what you set before training.",
        example="Random Forest: n_estimators=100 (hyperparameter), tree split thresholds (parameters learned from data).",
        common_mistakes=["Tuning too many hyperparameters at once", "Not using cross-validation for tuning", "Tuning on test data (use validation set)"],
        practice_exercise="Identify parameters and hyperparameters for Random Forest. 1. What does the model learn? 2. What do you set before training? 3. Which hyperparameters matter most?",
        quiz=[QuizQuestion(question="Which is a hyperparameter of KNN?", options=["The class labels", "k (number of neighbours)", "The distance to each neighbour", "The majority vote"], correct_index=1, explanation="k is set before training — it's a hyperparameter. The distances and votes are computed during prediction from the data.")],
        takeaways=["Parameters learned from data, hyperparameters set by you", "Use cross-validation for tuning", "Start with defaults, tune the most impactful first"],
        lab_module="classification",
    ),
    Topic(id="clf_13", title="Training a Classifier", section="classification", order=13, difficulty="beginner",
        objectives=["Follow the complete training workflow", "Build reproducible pipelines", "Evaluate on held-out data"],
        concept="Training workflow: (1) Split data, (2) Build preprocessing pipeline, (3) Fit on training data, (4) Predict on test data, (5) Evaluate. Pipeline prevents data leakage.",
        why_matters="A correct training workflow ensures your evaluation is honest. Data leakage produces models that look great but fail in production.",
        python_example="```python\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import train_test_split\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42, stratify=y\n)\n\npreprocessor = ColumnTransformer([\n    ('num', Pipeline([('imputer', SimpleImputer(strategy='median')),\n                      ('scaler', StandardScaler())]), num_cols),\n    ('cat', Pipeline([('imputer', SimpleImputer(strategy='most_frequent')),\n                      ('encoder', OneHotEncoder(handle_unknown='ignore'))]), cat_cols),\n])\n\npipeline = Pipeline([\n    ('preprocessor', preprocessor),\n    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))\n])\npipeline.fit(X_train, y_train)\nprint(f'Accuracy: {pipeline.score(X_test, y_test):.3f}')\n```",
        common_mistakes=["Fitting preprocessing on entire dataset before splitting", "Not using Pipeline (error-prone manual steps)", "Not setting random_state"],
        practice_exercise="Build a complete training pipeline: split, preprocess, train, evaluate. 1. Is it inside a Pipeline? 2. Does cross_val_score work? 3. Save the pipeline.",
        quiz=[QuizQuestion(question="What is the correct order for training a classifier?", options=["Train → Split → Preprocess → Evaluate", "Preprocess → Split → Train → Evaluate", "Split → Preprocess → Train → Evaluate", "Split → Train → Preprocess → Evaluate"], correct_index=2, explanation="Always split first, then preprocess (fit on train only), then train, then evaluate. Preprocessing before splitting causes data leakage.")],
        takeaways=["Always split first, then preprocess", "Use Pipeline to prevent data leakage", "Set random_state for reproducibility"],
        lab_module="classification",
    ),
    Topic(id="clf_14", title="Predictions", section="classification", order=14, difficulty="beginner",
        objectives=["Generate class predictions and probabilities", "Understand predict vs predict_proba", "Use probabilities for confidence assessment"],
        concept="Classifiers produce two outputs: class predictions (hard labels: 0 or 1) and probability predictions (soft labels: 0.73). Probabilities are more informative — they allow threshold adjustment.",
        why_matters="Probabilities allow you to adjust the classification threshold and measure confidence. A model that says '90% sure it's spam' is more useful than 'spam'.",
        python_example="```python\n# Hard predictions\nclasses = pipeline.predict(X_test)\n\n# Probabilities\nprobs = pipeline.predict_proba(X_test)\nprint(probs[:3])  # [[0.8, 0.2], [0.3, 0.7], [0.95, 0.05]]\n\n# Probability of positive class\nprob_positive = pipeline.predict_proba(X_test)[:, 1]\n```",
        common_mistakes=["Only using hard predictions when probabilities are available", "Not calibrating probabilities (some models produce poorly calibrated probs)", "Forgetting predict_proba returns ALL class probabilities"],
        practice_exercise="Get predictions and probabilities from a classifier. 1. What do the probabilities sum to for each sample? 2. How confident is the model on average? 3. Find the least confident predictions.",
        quiz=[QuizQuestion(question="What does predict_proba() return?", options=["Hard class labels", "A probability for each class, summing to 1.0", "The confidence of the prediction", "The error rate"], correct_index=1, explanation="predict_proba() returns a probability distribution over all classes for each sample. Each row sums to 1.0. This lets you see not just the predicted class, but how confident the model is.")],
        takeaways=["predict() gives class labels", "predict_proba() gives probabilities for ALL classes", "Use probabilities for threshold tuning and confidence assessment"],
        lab_module="classification",
    ),
    Topic(id="clf_15", title="Decision Boundaries", section="classification", order=15, difficulty="intermediate",
        objectives=["Visualise decision boundaries", "Understand how algorithms create boundaries", "Compare boundary shapes across algorithms"],
        concept="The decision boundary is where the model switches from predicting one class to another. Linear models create straight lines, trees create axis-parallel rectangles, SVM RBF creates smooth curves.",
        why_matters="Visualising boundaries reveals why an algorithm fails: linear models miss curved patterns, KNN overfits in noisy regions, etc.",
        python_example="```python\nfrom sklearn.inspection import DecisionBoundaryDisplay\nimport matplotlib.pyplot as plt\n\nmodel = LogisticRegression()\nmodel.fit(X_train[['age', 'fare']], y_train)\n\nDecisionBoundaryDisplay.from_estimator(\n    model, X_train[['age', 'fare']],\n    response_method='predict', cmap=plt.cm.RdYlBu, alpha=0.5\n)\nplt.scatter(X_train['age'], X_train['fare'], c=y_train, cmap=plt.cm.RdYlBu, edgecolor='black')\nplt.title('Decision Boundary')\nplt.show()\n```",
        common_mistakes=["Trying to visualise with >2 features (use PCA first)", "Misinterpreting the boundary as the 'true' separation"],
        practice_exercise="Visualise decision boundaries for LR and Decision Tree on 2 features. 1. How do the boundaries differ? 2. Which captures non-linear patterns? 3. Which might overfit?",
        quiz=[QuizQuestion(question="A Decision Tree creates decision boundaries that are:", options=["Smooth curves", "Straight diagonal lines", "Axis-parallel (horizontal/vertical) rectangles", "Circles"], correct_index=2, explanation="Decision trees split on one feature at a time (e.g., 'age > 30'), creating axis-parallel boundaries — rectangles aligned with the feature axes.")],
        takeaways=["Decision boundaries show where the model switches classes", "Linear → straight lines, trees → rectangles, SVM RBF → curves", "Visualise with 2 features or PCA"],
        lab_module="classification",
    ),
    Topic(id="clf_16", title="Class Imbalance", section="classification", order=16, difficulty="intermediate",
        objectives=["Identify class imbalance", "Understand why accuracy is misleading", "Apply remedies: class weights, resampling, appropriate metrics"],
        concept="Class imbalance: one class dominates (95% negative, 5% positive). A model that always predicts 'negative' gets 95% accuracy — completely useless. Accuracy is misleading here.",
        why_matters="Imbalanced data is common: fraud (0.1%), disease (2%), defects. Using accuracy leads to models that miss all positive cases.",
        python_example="```python\nprint(y_train.value_counts())\nprint(y_train.value_counts(normalize=True))\n\n# Remedy: class weights\nmodel = RandomForestClassifier(class_weight='balanced')\n\n# Remedy: use F1\nfrom sklearn.metrics import classification_report\nprint(classification_report(y_test, y_pred))\n```",
        common_mistakes=["Reporting only accuracy on imbalanced data", "Not checking class balance before training", "Oversampling test data (only oversample training)"],
        practice_exercise="Train on imbalanced data (90/10 split). 1. What is accuracy if you always predict class 0? 2. Train a model — what is F1? 3. Try class_weight='balanced'. How does F1 change?",
        quiz=[QuizQuestion(question="In a dataset with 99% class 0 and 1% class 1, a model that always predicts class 0 achieves 99% accuracy. Is this model useful?", options=["Yes — 99% is excellent", "No — it catches 0% of class 1 cases", "Yes — accuracy is the most important metric", "It depends on the model type"], correct_index=1, explanation="The model has perfect accuracy but zero recall on the minority class — it never catches any positive cases. For imbalanced data, accuracy is meaningless; use F1, precision, recall.")],
        takeaways=["Check class balance before training", "Use F1, precision, recall instead of accuracy", "class_weight='balanced' is the easiest fix"],
        lab_module="classification",
    ),
    Topic(id="clf_17", title="Probability Predictions", section="classification", order=17, difficulty="intermediate",
        objectives=["Understand probability calibration", "Compare calibrated vs uncalibrated probabilities", "Use calibration curves"],
        concept="Well-calibrated: among instances predicted with 70% probability, ~70% actually belong to the positive class. Some models (SVM, trees) produce poorly calibrated probabilities.",
        why_matters="Well-calibrated probabilities are essential for risk assessment. A model saying '80% cancer risk' should mean it 80% of the time.",
        python_example="```python\nfrom sklearn.calibration import calibration_curve\nimport matplotlib.pyplot as plt\n\nprob_true, prob_pred = calibration_curve(y_test, model.predict_proba(X_test)[:, 1], n_bins=10)\nplt.plot(prob_pred, prob_true, marker='o', label='Model')\nplt.plot([0, 1], [0, 1], '--', color='gray', label='Perfect')\nplt.xlabel('Mean predicted probability')\nplt.ylabel('Fraction of positives')\nplt.legend()\nplt.title('Calibration Curve')\n```",
        common_mistakes=["Assuming all models produce calibrated probabilities", "Using uncalibrated probabilities for risk assessment", "Not comparing calibration across models"],
        practice_exercise="Get probability predictions from a classifier. 1. Plot a calibration curve. 2. Is the model well-calibrated? 3. What does 'well-calibrated' mean in practice?",
        quiz=[QuizQuestion(question="Which classifier is naturally well-calibrated?", options=["Decision Tree", "Logistic Regression", "KNN with k=1", "Random Forest"], correct_index=1, explanation="Logistic Regression directly models probabilities via the sigmoid function, making it naturally well-calibrated. Trees and KNN produce probabilities based on proportions, which can be poorly calibrated.")],
        takeaways=["Calibration = predicted probability matches actual frequency", "Logistic Regression is naturally well-calibrated", "Use CalibratedClassifierCV for models that aren't"],
        lab_module="classification",
    ),
    Topic(id="clf_18", title="Classification Threshold", section="classification", order=18, difficulty="intermediate",
        objectives=["Understand the default 0.5 threshold", "Adjust threshold for business requirements", "Use precision-recall tradeoff"],
        concept="By default, models predict 'positive' when probability > 0.5. But 0.5 isn't always optimal. For cancer screening, lower the threshold to catch more cases (higher recall). For spam, raise it to avoid blocking real email (higher precision).",
        why_matters="The threshold directly controls the precision-recall tradeoff. Choosing the right threshold aligns the model with real-world costs.",
        python_example="```python\nfrom sklearn.metrics import precision_recall_curve\nimport numpy as np\n\nprobs = model.predict_proba(X_test)[:, 1]\nprecisions, recalls, thresholds = precision_recall_curve(y_test, probs)\n\n# F1-optimal threshold\nf1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-8)\noptimal_idx = np.argmax(f1_scores)\nprint(f'Optimal threshold: {thresholds[optimal_idx]:.3f}')\n```",
        common_mistakes=["Always using 0.5 without considering the problem", "Not adjusting threshold when class distribution changes in production", "Optimising threshold on test data instead of validation"],
        practice_exercise="Vary the classification threshold from 0.1 to 0.9. 1. Plot precision and recall vs threshold. 2. What threshold maximises F1? 3. For cancer detection, what threshold gives 95% recall?",
        quiz=[QuizQuestion(question="You lower the threshold from 0.5 to 0.3. What happens?", options=["Precision increases, recall decreases", "Both increase", "Precision decreases, recall increases", "Nothing changes"], correct_index=2, explanation="Lowering the threshold means more instances are classified as positive. This catches more true positives (higher recall) but also more false positives (lower precision).")],
        takeaways=["0.5 is a default, not a rule", "Lower threshold → more positives → higher recall, lower precision", "Choose threshold based on cost of false positives vs false negatives"],
        lab_module="classification",
    ),
    Topic(id="clf_19", title="Overfitting in Classification", section="classification", order=19, difficulty="intermediate",
        objectives=["Identify overfitting", "Distinguish training vs test performance", "Apply remedies: regularisation, pruning, simpler models"],
        concept="Overfitting: model memorises training data instead of learning patterns. Signs: high training accuracy but low test accuracy. The model fits noise as if it were signal.",
        why_matters="Overfitted models look perfect during development but fail on new data. Detecting and preventing overfitting is the core challenge of ML.",
        python_example="```python\ntrain_acc = model.score(X_train, y_train)\ntest_acc = model.score(X_test, y_test)\nprint(f'Train: {train_acc:.3f}, Test: {test_acc:.3f}')\nif train_acc - test_acc > 0.1:\n    print('WARNING: Possible overfitting!')\n\n# Remedy: regularisation\nmodel = LogisticRegression(C=0.1)  # C < 1 = more regularisation\n```",
        common_mistakes=["Only looking at training accuracy", "Not using cross-validation", "Using a model that's too complex for the data size"],
        practice_exercise="Compare train vs test accuracy for Decision Tree with depth in [2, 5, 10, 20, None]. 1. At what depth does the gap widen? 2. What does this tell you?",
        quiz=[QuizQuestion(question="Train accuracy = 1.0, test accuracy = 0.65. What's the problem?", options=["The model is underfitting", "The model is severely overfitting", "The test set is wrong", "The model needs more features"], correct_index=1, explanation="Perfect training accuracy with low test accuracy is the classic overfitting signature. The model memorised every training example (including noise) but can't generalise.")],
        takeaways=["High train + low test accuracy = overfitting", "Cross-validation provides honest estimates", "Remedies: simpler model, more data, regularisation"],
        lab_module="classification",
    ),
    Topic(id="clf_20", title="Classification Case Study", section="classification", order=20, difficulty="advanced",
        objectives=["Apply the complete classification workflow", "Compare multiple algorithms", "Document and justify model selection"],
        concept="Complete case study: load → EDA → preprocess → engineer features → train multiple models → evaluate → compare → select. Titanic survival prediction demonstrates the full workflow.",
        why_matters="Real projects require the complete workflow, not just model training. This case study shows how all pieces fit together.",
        example="Titanic case study:\n1. EDA: Age missing 19.8%, Fare right-skewed, Females survived more.\n2. Features: Title from Name, FamilySize from SibSp+Parch.\n3. Models: LR (78%), RF (81%), GB (83%).\n4. Winner: Gradient Boosting with 83% accuracy.",
        python_example="```python\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder\nfrom sklearn.ensemble import GradientBoostingClassifier\nfrom sklearn.model_selection import cross_val_score\n\n# Full pipeline\npipeline = Pipeline([\n    ('preprocessor', preprocessor),\n    ('classifier', GradientBoostingClassifier(n_estimators=100, random_state=42))\n])\n\n# Cross-validation\nscores = cross_val_score(pipeline, X, y, cv=5, scoring='f1')\nprint(f'F1: {scores.mean():.3f} ± {scores.std():.3f}')\n```",
        common_mistakes=["Not documenting why you chose a model", "Chasing highest accuracy without considering other metrics", "Not saving the final model for production"],
        practice_exercise="Complete a classification case study: EDA, preprocess, engineer features, train 3 models, evaluate, compare. 1. Which model wins? 2. What features matter? 3. Write a summary.",
        quiz=[QuizQuestion(question="In a case study, you get LR=78%, RF=81%, GB=83%. Why might you choose RF over GB?", options=["RF is always better", "GB might be too slow or complex for the 2% gain", "RF has higher accuracy", "GB doesn't work with classification"], correct_index=1, explanation="GB's 2% improvement over RF may not justify the added complexity, longer training time, and reduced interpretability. If RF is fast and interpretable enough, it's often the better practical choice.")],
        takeaways=["Follow: EDA → preprocess → engineer → train → evaluate → compare", "Always compare multiple algorithms", "Document decisions and metrics"],
        lab_module="classification",
    ),
]
