"""Data Loading curriculum — 16 topics."""

from learning import QuizQuestion, Topic

TOPICS = [
    Topic(
        id="dl_01", title="Introduction to Datasets", section="data_loading", order=1,
        difficulty="beginner",
        objectives=["Understand what a dataset is", "Identify common dataset formats", "Recognise rows and columns"],
        concept="A dataset is a structured collection of data, typically organised in rows (observations) and columns (features). In data science, datasets are the raw material we work with.",
        why_matters="Every data science project begins with a dataset. Understanding dataset structure is foundational — if you misread the data, everything downstream is wrong.",
        simple_explanation="Think of a dataset as a spreadsheet: each row is one record (e.g., one patient, one house sale) and each column is one attribute (e.g., age, price).",
        example="The Iris dataset has 150 rows (flowers) and 5 columns (4 measurements + species). Each row represents one flower, and the columns tell us its sepal length, sepal width, petal length, petal width, and species.",
        python_example="```python\nimport pandas as pd\ndf = pd.read_csv('iris.csv')\nprint(df.shape)  # (150, 5)\nprint(df.columns)  # Index(['sepal_length', 'sepal_width', ...])\n```",
        interpretation="shape returns (rows, columns). columns shows the feature names. Always check these first.",
        common_mistakes=["Confusing rows with columns when reading output", "Not checking if the file loaded correctly"],
        practice_exercise="Load the Titanic dataset and print its shape and column names.",
        quiz=[
            QuizQuestion("What does df.shape return?", ["Column names", "A tuple of (rows, columns)", "Data types", "First 5 rows"], 1, "shape returns a tuple: (number_of_rows, number_of_columns)."),
            QuizQuestion("A dataset has 1000 rows and 15 columns. How many observations are there?", ["15", "1015", "1000", "Cannot determine"], 2, "Rows represent observations. 1000 rows = 1000 observations."),
        ],
        takeaways=["Datasets are structured as rows × columns", "Always check shape and columns first", "Rows = observations, Columns = features"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_02", title="CSV Files", section="data_loading", order=2,
        difficulty="beginner",
        objectives=["Understand CSV format", "Read CSV files with pandas", "Handle common CSV issues"],
        concept="CSV (Comma-Separated Values) is the most common plain-text format for tabular data. Each line is a row, and values are separated by commas.",
        why_matters="CSV files are universal — they can be created by any spreadsheet or database. Most datasets you encounter will be CSVs.",
        simple_explanation="A CSV file is like a text file where commas separate the columns. The first row usually contains column headers.",
        example="A CSV file might look like:\n```\nName,Age,City\nAlice,30,NYC\nBob,25,LA\n```\nEach comma marks a column boundary. The first row is the header.",
        python_example="```python\nimport pandas as pd\n\ndf = pd.read_csv('data.csv')\ndf = pd.read_csv('data.csv', sep='\\t')  # tab-separated\ndf = pd.read_csv('data.csv', encoding='latin-1')  # handle special chars\ndf = pd.read_csv('data.csv', index_col=0)  # use first column as index\n```",
        interpretation="If you see garbled characters, try encoding='latin-1' or encoding='cp1252'. If columns are wrong, check sep parameter.",
        common_mistakes=["Forgetting sep='\\t' for TSV files", "Not checking encoding when characters look wrong", "Assuming the header row is always row 0"],
        practice_exercise="Load a CSV file. If it has tab separators, what parameter do you need to add?",
        quiz=[
            QuizQuestion("What separator does pd.read_csv use by default?", ["Tab", "Semicolon", "Comma", "Space"], 2, "CSV stands for Comma-Separated Values — the default separator is comma."),
            QuizQuestion("A file has garbled characters. What should you try first?", ["Change the separator", "Change the encoding", "Skip rows", "Use read_excel"], 1, "Garbled characters usually indicate an encoding mismatch. Try encoding='latin-1'."),
        ],
        takeaways=["CSV is comma-separated by default", "Use sep for other delimiters", "Check encoding if characters look wrong"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_03", title="Excel Files", section="data_loading", order=3,
        difficulty="beginner",
        objectives=["Read Excel files with pandas", "Handle multiple sheets", "Understand when to use Excel vs CSV"],
        concept="Excel files (.xlsx, .xls) store data in sheets with formatting, formulas, and multiple tabs. Pandas can read them with read_excel().",
        why_matters="Many business datasets come as Excel files. You need to handle them, but also understand their limitations (formatting, formulas, size).",
        simple_explanation="Excel files can have multiple sheets (like tabs in a workbook). You specify which sheet to read.",
        example="A sales workbook might have separate sheets for 2022, 2023, and 2024 data. You can load just the 2024 sheet: `pd.read_excel('sales.xlsx', sheet_name='2024')`.",
        python_example="```python\nimport pandas as pd\n\ndf = pd.read_excel('data.xlsx')  # first sheet\ndf = pd.read_excel('data.xlsx', sheet_name='Sales')  # named sheet\nsheets = pd.ExcelFile('data.xlsx').sheet_names  # list all sheets\n```",
        interpretation="Excel files are larger and slower than CSVs. For data science, prefer CSV for simplicity and speed.",
        common_mistakes=["Not specifying sheet_name when there are multiple sheets", "Reading formatted cells (merged cells cause issues)", "Using Excel for very large datasets (>1M rows)"],
        practice_exercise="Load an Excel file and list all sheet names. Load the second sheet.",
        quiz=[
            QuizQuestion("What is a key difference between CSV and Excel files?", ["CSV has multiple sheets, Excel has one", "Excel has multiple sheets, CSV has one", "They are identical", "CSV supports formulas"], 1, "Excel files support multiple sheets; CSV files are flat (single sheet)."),
        ],
        takeaways=["Use sheet_name to select specific sheets", "CSV is simpler and faster for data science", "Excel formatting can cause loading issues"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_04", title="Loading Data with Pandas", section="data_loading", order=4,
        difficulty="beginner",
        objectives=["Use pd.read_csv() and pd.read_excel()", "Handle different file formats", "Verify data loaded correctly"],
        concept="Pandas is the primary library for loading tabular data in Python. It supports CSV, Excel, JSON, Parquet, SQL, and many more formats.",
        why_matters="Data loading is step zero. If it fails or loads incorrectly, all downstream analysis is wrong.",
        simple_explanation="pandas.read_csv() reads a CSV file into a DataFrame — a table you can work with in Python.",
        example="After loading Titanic with `pd.read_csv('titanic.csv')`, you get a DataFrame with 891 rows and 12 columns including Name, Age, Fare, and Survived.",
        python_example="```python\nimport pandas as pd\n\n# CSV\ndf = pd.read_csv('data.csv')\n# Excel\ndf = pd.read_excel('data.xlsx')\n# JSON\ndf = pd.read_json('data.json')\n# From URL\ndf = pd.read_csv('https://example.com/data.csv')\n```",
        interpretation="After loading, always check: df.shape, df.head(), df.dtypes, df.isnull().sum().",
        common_mistakes=["Not checking if loading succeeded", "Using wrong file path", "Not handling encoding issues", "Forgetting to import pandas"],
        practice_exercise="Load the Iris CSV dataset and verify it has 150 rows and 5 columns.",
        quiz=[
            QuizQuestion("Which function loads a CSV file into a DataFrame?", ["pd.load_csv()", "pd.read_csv()", "pd.open_csv()", "pd.import_csv()"], 1, "The correct function is pd.read_csv()."),
        ],
        takeaways=["pandas supports many formats: CSV, Excel, JSON, Parquet", "Always verify after loading", "Check the file path is correct"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_05", title="Accessing Data", section="data_loading", order=5,
        difficulty="beginner",
        objectives=["Distinguish rows from columns", "Understand indexing", "Access specific rows and columns"],
        concept="In a DataFrame, rows are indexed (0, 1, 2, ...) and columns have names. You can access subsets using loc (label-based) and iloc (integer-based).",
        why_matters="Being able to select specific data is essential for analysis, filtering, and preprocessing.",
        simple_explanation="Rows = individual records. Columns = attributes of those records. df.loc[0] gives the first row; df['age'] gives the age column.",
        example="From Titanic: `df[df['Age'] > 30]` gives all passengers older than 30. `df.loc[df['Survived'] == 1, ['Name', 'Age']]` shows names and ages of survivors.",
        python_example="```python\ndf.head()      # first 5 rows\ndf.tail()      # last 5 rows\ndf['age']      # single column\ndf[['age', 'income']]  # multiple columns\ndf.loc[0]      # first row by label\ndf.iloc[0]     # first row by position\ndf.iloc[0:5]   # first 5 rows by position\n```",
        interpretation="loc uses labels (including column names), iloc uses integer positions. When in doubt, use iloc for positional access.",
        common_mistakes=["Confusing loc and iloc", "Trying to access a column that doesn't exist", "Forgetting that slicing is inclusive on the left, exclusive on the right"],
        practice_exercise="From the Titanic dataset, select the 'Age' column and the first 10 rows.",
        quiz=[
            QuizQuestion("What does df.iloc[0:5] return?", ["Rows 0 through 5 (6 rows)", "Rows 1 through 5 (5 rows)", "Columns 0 through 5", "The first 5 columns"], 0, "iloc slicing is inclusive on left, exclusive on right: iloc[0:5] returns rows at positions 0,1,2,3,4 (5 rows)."),
        ],
        takeaways=["Rows are records, columns are attributes", "loc = label-based, iloc = position-based", "Always check column names before selecting"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_06", title="Data Types", section="data_loading", order=6,
        difficulty="beginner",
        objectives=["Identify numerical vs categorical dtypes", "Understand int64, float64, object, bool, category", "Convert between types"],
        concept="Every column has a data type (dtype) that determines what operations are possible. Common types: int64 (integers), float64 (decimals), object (strings), bool (True/False), category.",
        why_matters="Wrong dtypes break models. A number stored as string cannot be scaled. A category stored as integer implies ordering. Always verify.",
        simple_explanation="int/float = numbers (you can do math). object/category = text (need encoding). bool = True/False.",
        example="In Titanic, 'Survived' is int64 (0 or 1), 'Age' is float64 (decimal values), and 'Name' is object (strings). If 'Age' shows as object, there's likely a non-numeric value like 'Unknown'.",
        python_example="```python\nprint(df.dtypes)           # show all dtypes\ndf['age'] = df['age'].astype(float)  # convert type\ndf['color'] = df['color'].astype('category')  # make categorical\npd.to_numeric(df['price'], errors='coerce')  # force numeric\n```",
        interpretation="object dtype usually means strings. If a numeric column is object, check for non-numeric characters.",
        common_mistakes=["Not checking dtypes after loading", "Forcing conversion without checking for errors", "Treating zip codes as numbers"],
        practice_exercise="Check the dtypes of the Titanic dataset. Which columns are numeric? Which are categorical?",
        quiz=[
            QuizQuestion("A column shows dtype 'object' but should be numeric. What should you check first?", ["If the column name is correct", "For non-numeric characters like '$' or ','", "If the file is CSV", "If pandas is installed"], 1, "Non-numeric characters (like '$10.50' or 'N/A') prevent numeric conversion."),
        ],
        takeaways=["Always check dtypes with df.dtypes", "object usually means strings", "Convert types carefully — check for errors first"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_07", title="Numerical vs Categorical Data", section="data_loading", order=7,
        difficulty="beginner",
        objectives=["Classify columns as numerical or categorical", "Understand the difference in modelling", "Identify mixed types"],
        concept="Numerical data represents quantities (age, income, temperature). Categorical data represents groups (color, city, yes/no). The distinction determines preprocessing steps.",
        why_matters="Numerical features can be scaled and used directly. Categorical features must be encoded. Mixing them up causes errors.",
        simple_explanation="If you can take an average, it's numerical. If you can only count, it's categorical.",
        example="In Titanic: 'Age' (29.7 average makes sense) is numerical. 'Sex' (male/female) is categorical. 'Pclass' (1/2/3) looks numerical but is actually categorical — you can't average passenger classes meaningfully.",
        python_example="```python\nnum_cols = df.select_dtypes('number').columns.tolist()\ncat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()\nprint(f'Numerical: {num_cols}')\nprint(f'Categorical: {cat_cols}')\n```",
        interpretation="Some columns blur the line (e.g., zip codes are numbers but should be categorical). Use domain knowledge.",
        common_mistakes=["Treating categorical IDs as numerical", "Ignoring categorical columns in preprocessing", "Number of unique values can mislead — 1000 zip codes look numerical but are categorical"],
        practice_exercise="Separate the Titanic dataset into numerical and categorical columns. How many of each?",
        quiz=[
            QuizQuestion("A column 'ZipCode' has integer values. Is it numerical or categorical?", ["Numerical — it's integers", "Categorical — zip codes represent regions, not quantities", "Both", "Neither"], 1, "Zip codes are identifiers for regions. You cannot meaningfully average them."),
        ],
        takeaways=["Numerical = quantities, Categorical = groups", "Use domain knowledge for ambiguous cases", "Always separate before preprocessing"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_08", title="Dataset Shape and Structure", section="data_loading", order=8,
        difficulty="beginner",
        objectives=["Use df.shape, df.info(), df.describe()", "Understand memory usage", "Assess dataset size"],
        concept="Dataset structure includes: shape (rows × columns), memory usage, column types, and non-null counts. df.info() gives a comprehensive summary.",
        why_matters="Large datasets may cause memory issues. Datasets with many columns need feature selection. Understanding structure guides your approach.",
        simple_explanation="df.shape tells you size. df.info() tells you what's inside. df.describe() tells you statistical properties.",
        example="California Housing dataset: `df.shape` = (20640, 8) — 20K rows, 8 features. `df.info()` shows no missing values and ~1.3MB memory. `df.describe()` shows median income ranges from 0.5 to 15.",
        python_example="```python\ndf.shape          # (rows, columns)\ndf.info()         # column names, dtypes, non-null counts, memory\ndf.describe()     # statistical summary of numerical columns\ndf.memory_usage(deep=True).sum()  # total memory in bytes\n```",
        interpretation="If info() shows many columns with few non-null values, you have missing data. If memory is large, consider sampling.",
        common_mistakes=["Ignoring memory usage for large datasets", "Not noticing that info() reveals missing values", "Forgetting describe() only summarises numerical columns"],
        practice_exercise="Use df.info() on the California Housing dataset. How many columns have missing values?",
        quiz=[
            QuizQuestion("df.describe() summarises which columns?", ["All columns", "Only numerical columns", "Only categorical columns", "Only the first 5 columns"], 1, "By default, describe() only summarises numerical columns. Use include='all' for all columns."),
        ],
        takeaways=["shape gives dimensions", "info() reveals types and nulls", "describe() shows statistics"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_09", title="Inspecting Data", section="data_loading", order=9,
        difficulty="beginner",
        objectives=["Preview data with head/tail/sample", "Spot obvious data issues visually", "Use sample() for random inspection"],
        concept="head() shows the first rows, tail() shows the last, sample() shows random rows. These are your first look at actual data values.",
        why_matters="Statistical summaries hide data quality issues. Looking at actual values reveals formatting problems, encoding issues, and unexpected values.",
        simple_explanation="Always look at your data before analysing it. head() is your magnifying glass.",
        example="Loading Titanic and running `df.head()` might reveal: 'Age' has NaN values, 'Cabin' is mostly empty, and 'Name' contains titles like 'Mr' and 'Mrs' that could be extracted.",
        python_example="```python\ndf.head(10)       # first 10 rows\ndf.tail(5)        # last 5 rows\ndf.sample(10)     # 10 random rows\ndf.sample(frac=0.1)  # 10% of data randomly\n```",
        interpretation="Look for: garbled text (encoding), unexpected NaN values, columns that don't match their names, and outliers.",
        common_mistakes=["Only looking at head() — problems may be in the middle or tail", "Not using sample() — head() always shows the same rows", "Assuming data looks correct without checking types"],
        practice_exercise="Load Titanic and show 10 random rows. Do you see any obvious issues?",
        quiz=[
            QuizQuestion("Which function shows random rows from a DataFrame?", ["head()", "tail()", "sample()", "random()"], 2, "sample() returns random rows from the DataFrame."),
        ],
        takeaways=["head() for first rows, tail() for last, sample() for random", "Visual inspection catches issues statistics miss", "Always sample before analysing"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_10", title="Data Information with info()", section="data_loading", order=10,
        difficulty="beginner",
        objectives=["Read df.info() output", "Identify missing values", "Understand memory usage"],
        concept="df.info() provides a concise summary: column names, non-null counts, dtypes, and total memory usage. It's the quickest way to assess data quality.",
        why_matters="info() instantly reveals: how many missing values exist, what types columns have, and whether the dataset fits in memory.",
        simple_explanation="df.info() is like a health check for your dataset — it tells you what's there and what's missing.",
        example="Running `df.info()` on Titanic shows: Age has 714 non-null out of 891 (177 missing), Cabin has only 204 non-null (687 missing!), and Embarked has 889 (2 missing).",
        python_example="```python\ndf.info()\n# <class 'pandas.core.frame.DataFrame'>\n# RangeIndex: 891 entries, 0 to 890\n# Data columns (total 12 columns):\n#  #   Column    Non-Null  Count  Dtype  \n# ---  ------    --------  -----  -----  \n# 0   PassengerId  891 non-null  int64  \n# 5   Age          714 non-null  float64  ← 177 missing!\n```",
        interpretation="Non-Null Count < total rows means missing values. 'object' dtype usually means strings.",
        common_mistakes=["Skimming past the non-null counts", "Not noticing that some columns have very few non-null values"],
        practice_exercise="Run df.info() on Titanic. Which column has the most missing values?",
        quiz=[
            QuizQuestion("df.info() shows 'Age  714 non-null  float64' for an 891-row dataset. What does this mean?", ["Age is always float64", "177 rows have missing Age values", "Age has 714 unique values", "Age is the most important column"], 1, "714 non-null out of 891 total means 891-714 = 177 missing values."),
        ],
        takeaways=["info() shows non-null counts — gaps mean missing data", "Check dtypes here first", "Memory usage helps with large datasets"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_11", title="Descriptive Statistics", section="data_loading", order=11,
        difficulty="beginner",
        objectives=["Read df.describe() output", "Understand mean, std, quartiles", "Spot outliers from statistics"],
        concept="df.describe() computes count, mean, std, min, 25%, 50%, 75%, and max for each numerical column. It gives a statistical fingerprint of your data.",
        why_matters="Statistics reveal the range, central tendency, and spread of each feature. Large gaps between 75% and max suggest outliers.",
        simple_explanation="describe() answers: How big are the numbers? How spread out? Are there extreme values?",
        example="Titanic Fare: mean=32.2, std=49.7 (very spread out), max=512.3 while 75%=31.0. This huge gap between 75% and max indicates extreme fare outliers.",
        python_example="```python\ndf.describe()\n#         age    fare    survived\n# count  714.0   891.0   891.0\n# mean    29.7    32.2     0.38\n# std     14.5    49.7     0.49\n# min      0.4     0.0     0.0\n# 25%     20.1     7.9     0.0\n# 50%     28.0    14.5     0.0\n# 75%     38.0    31.0     1.0\n# max     80.0   512.3     1.0\n```",
        interpretation="If max >> 75%, there may be outliers. If std > mean, data is highly variable. If count < total rows, there are missing values.",
        common_mistakes=["Not noticing outlier indicators (max >> 75%)", "Comparing statistics across columns with different scales", "Forgetting that describe() excludes non-numerical columns by default"],
        practice_exercise="Use describe() on the Wine Quality dataset. Which feature has the highest standard deviation relative to its mean?",
        quiz=[
            QuizQuestion("In describe() output, if max is much larger than 75%, what might this indicate?", ["The data is normally distributed", "There may be outliers", "The data is missing", "The column should be dropped"], 1, "A large gap between the 75th percentile and max suggests outlier values."),
        ],
        takeaways=["describe() gives statistical summary", "max >> 75% suggests outliers", "std/mean > 1 means high variability"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_12", title="Missing Values", section="data_loading", order=12,
        difficulty="beginner",
        objectives=["Count missing values per column", "Calculate missing percentage", "Visualise missing data patterns"],
        concept="Missing values (NaN, None, empty cells) occur when data wasn't recorded. They must be handled before modelling.",
        why_matters="Most algorithms cannot handle missing data. Even if they run, missing values introduce bias and reduce accuracy.",
        simple_explanation="Missing values are holes in your data. You need to decide: fill them in (impute) or remove the affected rows/columns.",
        example="In Titanic: Age is missing for 177 passengers (19.9%), Cabin for 687 (77.1%), and Embarked for 2 (0.2%). Cabin has so many missing values that it may need to be dropped entirely.",
        python_example="```python\n# Count per column\ndf.isnull().sum()\n# Percentage\ndf.isnull().mean() * 100\n# Total missing\ndf.isnull().sum().sum()\n# Rows with any missing\ndf.isnull().any(axis=1).sum()\n# Visualise\ndf.isnull().sum().sort_values(ascending=False).plot(kind='bar')\n```",
        interpretation="If a column has >50% missing, consider dropping it. If <5%, dropping rows may be acceptable. Otherwise, impute.",
        common_mistakes=["Ignoring missing values and hoping the model handles them", "Dropping too many rows (>20%)", "Not checking if missing values follow a pattern"],
        practice_exercise="Calculate the percentage of missing values in each column of the Titanic dataset. Which column has the most?",
        quiz=[
            QuizQuestion("A column has 60% missing values. What is the best first step?", ["Fill with mean", "Fill with 0", "Consider dropping the column", "Ignore it"], 2, "With 60% missing, the column has too little information to be useful. Consider dropping it."),
        ],
        takeaways=["df.isnull().sum() counts missing per column", "High missing % → consider dropping", "Always check before modelling"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_13", title="Duplicate Records", section="data_loading", order=13,
        difficulty="beginner",
        objectives=["Detect duplicate rows", "Understand exact vs partial duplicates", "Decide whether to remove duplicates"],
        concept="Duplicate rows are exact copies of other rows. They inflate statistics and can cause data leakage if both copies end up in train and test sets.",
        why_matters="Duplicates bias model training — the model sees the same examples twice, overestimating its performance.",
        simple_explanation="Duplicate = same data entered twice. Remove them to get a clean, accurate dataset.",
        example="If the same patient record appears twice in a medical dataset, the model might learn that specific patient's symptoms twice, making it overconfident about similar cases.",
        python_example="```python\ndf.duplicated().sum()  # count duplicates\ndf.duplicated()        # boolean mask\ndf.drop_duplicates()   # remove duplicates\ndf.drop_duplicates(subset=['name', 'age'])  # partial match\n```",
        interpretation="If duplicates are legitimate (e.g., same person appears twice for different events), don't remove them.",
        common_mistakes=["Removing duplicates when they're legitimate", "Not checking before train/test split", "Forgetting to reset index after dropping"],
        practice_exercise="Check the Titanic dataset for duplicates. Are there any? What percentage?",
        quiz=[
            QuizQuestion("You find 100 exact duplicate rows in your dataset. What should you do first?", ["Always remove them", "Investigate why they exist", "Keep only the first one", "Report to your manager"], 1, "First investigate: are they data entry errors or legitimate duplicates? Then decide."),
        ],
        takeaways=["df.duplicated().sum() counts exact duplicates", "Always investigate before removing", "Duplicates bias model training"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_14", title="Data Quality", section="data_loading", order=14,
        difficulty="beginner",
        objectives=["Perform a systematic quality check", "Identify common data issues", "Create a quality checklist"],
        concept="Data quality checks combine: shape inspection, dtype verification, missing value analysis, duplicate detection, range validation, and consistency checks.",
        why_matters="Garbage in, garbage out. Data quality issues compound — one wrong column can ruin an entire model.",
        simple_explanation="Before any analysis, run a checklist: Is the data complete? Consistent? Correct? Current?",
        example="Quality check on Titanic reveals: 891 rows, 12 columns, Age missing 19.9%, Cabin missing 77.1%, 0 duplicates, Age ranges 0.4-80 (reasonable), Fare has extreme outliers.",
        python_example="```python\n# Quality checklist\ndef quality_check(df):\n    print(f'Shape: {df.shape}')\n    print(f'\\nMissing values:\\n{df.isnull().sum()}')\n    print(f'\\nDuplicates: {df.duplicated().sum()}')\n    print(f'\\nData types:\\n{df.dtypes}')\n    print(f'\\nStatistics:\\n{df.describe()}')\nquality_check(df)\n```",
        interpretation="Run this check on every new dataset. Issues found early save hours of debugging later.",
        common_mistakes=["Skipping quality checks when data 'looks fine'", "Only checking one aspect (e.g., only missing values)", "Not documenting quality issues found"],
        practice_exercise="Write a quality check function and run it on the Breast Cancer dataset. What issues do you find?",
        quiz=[
            QuizQuestion("Which is NOT a standard data quality check?", ["Missing value analysis", "Duplicate detection", "Model accuracy", "Range validation"], 2, "Model accuracy is a modelling step, not a data quality check."),
        ],
        takeaways=["Always quality-check new data", "Check: shape, types, missing, duplicates, ranges", "Document issues found"],
        lab_module="dataset_explorer",
    ),
    Topic(
        id="dl_15", title="Train/Test Data Concept", section="data_loading", order=15,
        difficulty="beginner",
        objectives=["Understand why we split data", "Learn the 80/20 convention", "Understand data leakage"],
        concept="We split data into training (to teach the model) and testing (to evaluate it). Testing on data the model has seen gives meaningless results.",
        why_matters="If you evaluate on training data, you measure memorisation, not generalisation. The test set simulates unseen future data.",
        simple_explanation="Train = homework (model learns). Test = exam (model proves it learned). Never let the model see the exam before the test.",
        example="With Titanic's 891 rows: 713 for training (80%) teaches the model patterns. 178 for testing (20%) evaluates if it generalises. If you train on all 891 and test on the same 891, accuracy looks great but the model fails on new passengers.",
        python_example="```python\nfrom sklearn.model_selection import train_test_split\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\nprint(f'Train: {len(X_train)}, Test: {len(X_test)}')\n```",
        interpretation="80/20 is standard. For large datasets, 90/10 or even 95/5 is fine. For small datasets, use cross-validation instead.",
        common_mistakes=["Evaluating on training data", "Fitting preprocessing before splitting (data leakage)", "Not setting random_state (non-reproducible splits)"],
        practice_exercise="Split the Iris dataset 80/20. How many samples are in each set?",
        quiz=[
            QuizQuestion("Why should you split data before preprocessing?", ["To save time", "To prevent data leakage — test data statistics shouldn't influence training", "It doesn't matter", "To use less memory"], 1, "If you scale using test data statistics, the model indirectly sees test information — this is data leakage."),
        ],
        takeaways=["Always split before preprocessing", "Train = learn, Test = evaluate", "Set random_state for reproducibility"],
        lab_module="preprocessing",
    ),
    Topic(
        id="dl_16", title="Common Data Loading Mistakes", section="data_loading", order=16,
        difficulty="beginner",
        objectives=["Recognise frequent loading errors", "Debug common issues", "Develop good loading habits"],
        concept="Common mistakes include: wrong file path, wrong separator, wrong encoding, not checking output, and loading the wrong file.",
        why_matters="Loading errors often fail silently — the data loads but is wrong (wrong columns, wrong types, truncated data).",
        simple_explanation="The most common mistake is not checking what you loaded. Always verify shape, head(), and dtypes.",
        example="Loading 'titanic.tsv' (tab-separated) with default `pd.read_csv()` gives shape (891, 1) — all data in one column. Adding `sep='\\t'` fixes it to (891, 12).",
        python_example="```python\n# Common fixes\ndf = pd.read_csv('data.csv', sep='\\t')           # tab-separated\ndf = pd.read_csv('data.csv', encoding='latin-1')  # encoding\ndf = pd.read_csv('data.csv', skiprows=1)          # skip header row\ndf = pd.read_csv('data.csv', na_values=['NA', '-'])  # custom NA\n\n# Always verify\nassert df.shape[0] > 0, 'Dataset is empty!'\nassert df.shape[1] > 1, 'Only one column loaded!'\n```",
        interpretation="If shape is (N, 1) when you expect many columns, the separator is probably wrong. If dtypes are all 'object', numbers may be strings.",
        common_mistakes=["Wrong separator gives (N, 1) shape", "Not checking — loading 'garbage' silently", "Using wrong file path without error"],
        practice_exercise="Load a CSV that uses tab separators. What error or wrong result do you get without sep='\\t'?",
        quiz=[
            QuizQuestion("You load a CSV and get shape (1000, 1) when you expected (1000, 10). What's wrong?", ["The file has too many rows", "The separator is probably wrong (e.g., tab instead of comma)", "The file is corrupt", "pandas is broken"], 1, "Shape (N, 1) means all data is in one column — the separator didn't split properly."),
        ],
        takeaways=["Always verify shape after loading", "Wrong separator → (N, 1) shape", "Check dtypes for unexpected types"],
        lab_module="dataset_explorer",
    ),
]
