"""EDA curriculum — 20 topics."""

from learning import QuizQuestion, Topic

TOPICS = [
    Topic(id="eda_01", title="What is EDA?", section="eda", order=1, difficulty="beginner",
        objectives=["Define EDA", "Understand its place in the data science pipeline"],
        concept="Exploratory Data Analysis (EDA) is the process of visually and statistically examining data to uncover patterns, spot anomalies, and form hypotheses before modelling.",
        why_matters="EDA prevents costly mistakes. Modelling without EDA is like navigating without a map — you might go in the wrong direction entirely.",
        simple_explanation="EDA = looking at your data from every angle before making any decisions about it.",
        example="Before predicting house prices, EDA reveals that 'garage' columns have 50% missing values and 'pool' is almost always empty — insights that change your approach.",
        python_example="```python\ndf.describe()  # statistics\ndf.hist()      # distributions\ndf.corr()      # correlations\n```",
        common_mistakes=["Skipping EDA and going straight to modelling", "Only looking at summary statistics without visualisation", "Not checking for data quality issues"],
        practice_exercise="Load Titanic and create a 3-question EDA plan. What would you investigate first?",
        quiz=[
            QuizQuestion("When should EDA be performed?", ["After model training", "Before any modelling", "Only when results are bad", "During deployment"], 1, "EDA always comes before modelling — it guides all subsequent decisions."),
        ],
        takeaways=["EDA = visualise and statistically examine data before modelling", "Catches issues early", "Guides preprocessing and feature choices"],
        lab_module="eda",
    ),
    Topic(id="eda_02", title="Purpose of EDA", section="eda", order=2, difficulty="beginner",
        objectives=["Understand EDA goals", "Identify what EDA reveals"],
        concept="EDA serves five purposes: (1) detect errors, (2) understand distributions, (3) find relationships, (4) check assumptions, (5) generate hypotheses.",
        why_matters="Each purpose prevents a specific class of modelling error. Without EDA, you won't know if your data is biased, your features are correlated, or your target is skewed.",
        simple_explanation="EDA answers: Is my data clean? What does it look like? What drives the target?",
        example="Titanic EDA reveals: Survival rate is 38% overall, but 74% for females vs 19% for males. This massive difference means 'Sex' will be a powerful predictor.",
        python_example="```python\n# Quick EDA overview\ndf.describe()\ndf['Survived'].value_counts(normalize=True)\ndf.groupby('Sex')['Survived'].mean()\n```",
        common_mistakes=["Treating EDA as a checkbox rather than an iterative process", "Not recording findings for later reference"],
        practice_exercise="List 3 questions EDA should answer for the California Housing dataset.",
        quiz=[
            QuizQuestion("Which is NOT a purpose of EDA?", ["Detect errors", "Train the best model", "Find relationships", "Check assumptions"], 1, "EDA explores data — model training comes later."),
        ],
        takeaways=["EDA detects errors, reveals distributions, finds relationships", "It's iterative, not one-time", "Findings guide all downstream decisions"],
        lab_module="eda",
    ),
    Topic(id="eda_03", title="Univariate Analysis", section="eda", order=3, difficulty="beginner",
        objectives=["Analyse one variable at a time", "Use histograms and box plots", "Understand central tendency and spread"],
        concept="Univariate analysis examines one variable in isolation: its distribution, central tendency (mean/median/mode), spread (std/IQR), and shape (skewness).",
        why_matters="Understanding each variable individually is the foundation for understanding relationships between variables.",
        simple_explanation="Univariate = 'uni' (one) + 'variate' (variable). Look at one thing at a time.",
        example="Analysing Titanic's Age: mean=29.7, median=28.0, std=14.5. The mean is slightly higher than median, suggesting slight right skewness. Range is 0.4 to 80 years.",
        python_example="```python\ndf['age'].hist(bins=30)          # distribution\ndf['age'].describe()             # statistics\ndf['age'].skew()                 # skewness\ndf['age'].value_counts().head()  # for categorical\n```",
        common_mistakes=["Only computing statistics without visualising", "Using mean when median is more appropriate (skewed data)"],
        practice_exercise="Perform univariate analysis on the 'Fare' column of Titanic. Is it skewed?",
        quiz=[
            QuizQuestion("For a heavily right-skewed distribution, which is a better measure of centre?", ["Mean", "Median", "Mode", "Standard deviation"], 1, "Median is robust to outliers and skewness; mean is pulled toward the tail."),
        ],
        takeaways=["Univariate = analyse one variable", "Use histogram + describe()", "Check skewness to choose mean vs median"],
        lab_module="eda",
    ),
    Topic(id="eda_04", title="Bivariate Analysis", section="eda", order=4, difficulty="beginner",
        objectives=["Examine relationships between two variables", "Use scatter plots and cross-tabs", "Identify correlations"],
        concept="Bivariate analysis examines the relationship between two variables: correlation (numerical-numerical), cross-tabulation (categorical-categorical), or group comparisons (numerical-categorical).",
        why_matters="Bivariate analysis reveals which features relate to the target — the foundation of feature selection.",
        simple_explanation="Bivariate = two variables at once. Does X affect Y? How strongly?",
        example="Titanic: Grouping Age by Survived shows survivors average 28.0 years vs non-survivors 30.3 years. Younger passengers had slightly higher survival rates.",
        python_example="```python\n# Numerical vs Numerical\ndf.plot.scatter(x='age', y='fare')\ndf['age'].corr(df['fare'])\n\n# Numerical vs Categorical\ndf.groupby('survived')['age'].mean()\n\n# Categorical vs Categorical\npd.crosstab(df['sex'], df['survived'])\n```",
        common_mistakes=["Confusing correlation with causation", "Not checking statistical significance", "Using scatter plots for two categorical variables"],
        practice_exercise="Plot Age vs Fare on Titanic. Is there a correlation? Is it meaningful?",
        quiz=[
            QuizQuestion("Which plot shows the relationship between two numerical variables?", ["Bar chart", "Scatter plot", "Histogram", "Pie chart"], 1, "Scatter plots show the relationship between two numerical variables."),
        ],
        takeaways=["Bivariate = two variables", "Scatter for num-num, crosstab for cat-cat", "Correlation ≠ causation"],
        lab_module="eda",
    ),
    Topic(id="eda_05", title="Multivariate Analysis", section="eda", order=5, difficulty="intermediate",
        objectives=["Analyse 3+ variables simultaneously", "Use pair plots and heatmaps", "Understand interaction effects"],
        concept="Multivariate analysis examines three or more variables simultaneously, revealing interaction effects that bivariate analysis misses.",
        why_matters="Real-world relationships involve multiple variables. A feature may correlate with the target only when another feature is at a certain level.",
        simple_explanation="Multivariate = many variables at once. Two features together may tell a story that neither tells alone.",
        example="Titanic: Age alone has weak correlation with Survival. ButAge + Sex together reveals that young females had 75% survival vs young males at 40% — a strong interaction effect.",
        python_example="```python\n# Pair plot (all numerical columns)\nimport seaborn as sns\nsns.pairplot(df[['age', 'fare', 'survived']], hue='survived')\n\n# Correlation heatmap\nimport matplotlib.pyplot as plt\nplt.figure(figsize=(10,8))\nplt.imshow(df.select_dtypes('number').corr(), cmap='coolwarm')\nplt.colorbar()\n```",
        common_mistakes=["Trying to visualise too many variables at once", "Not using PCA to reduce dimensions first"],
        practice_exercise="Create a correlation heatmap of the Iris dataset. Which two features are most correlated?",
        quiz=[
            QuizQuestion("What does a correlation heatmap show?", ["Missing values", "Relationships between all numerical pairs", "Data types", "Model accuracy"], 1, "A correlation heatmap shows the correlation coefficient between every pair of numerical features."),
        ],
        takeaways=["Multivariate reveals interaction effects", "Pair plots and heatmaps are key tools", "Use PCA for many dimensions"],
        lab_module="eda",
    ),
    Topic(id="eda_06", title="Numerical Analysis", section="eda", order=6, difficulty="beginner",
        objectives=["Analyse numerical distributions", "Compute descriptive statistics", "Identify skewness and kurtosis"],
        concept="Numerical variables have meaningful numeric values. Analyse them with histograms, box plots, and descriptive statistics (mean, median, std, quartiles).",
        why_matters="Numerical features often carry the most information for regression and are the easiest to work with in modelling.",
        simple_explanation="If you can compute an average, it's numerical. Analyse: distribution shape, centre, spread, and outliers.",
        example="California Housing: 'median_income' ranges 0.5-15 (highly variable), 'housing_age' ranges 1-52 (more uniform), 'rooms' averages 5.4 with std=1.3. Income is most skewed.",
        python_example="```python\ndf.select_dtypes('number').describe()\ndf['age'].hist(bins=30, edgecolor='black')\nprint(f'Skewness: {df[\"age\"].skew():.2f}')\nprint(f'Kurtosis: {df[\"age\"].kurtosis():.2f}')\n```",
        common_mistakes=["Ignoring skewness — it affects model performance", "Not checking for impossible values (negative age, etc.)"],
        practice_exercise="Analyse all numerical columns in California Housing. Which is most skewed?",
        quiz=[
            QuizQuestion("A skewness of 2.5 indicates:", ["Symmetric distribution", "Moderately skewed", "Highly right-skewed", "Uniform distribution"], 2, "Skewness > 1 indicates high right skewness."),
        ],
        takeaways=["Use describe() + histogram", "Skewness affects scaling and model choice", "Check for impossible values"],
        lab_module="eda",
    ),
    Topic(id="eda_07", title="Categorical Analysis", section="eda", order=7, difficulty="beginner",
        objectives=["Analyse categorical distributions", "Compute value counts and frequencies", "Visualise with bar charts"],
        concept="Categorical variables represent groups. Analyse them with value counts, frequency tables, and bar charts.",
        why_matters="Categorical features often drive classification targets. Understanding their distribution prevents class imbalance issues.",
        simple_explanation="Categorical = categories/groups. How many categories? How balanced? Any rare categories?",
        example="Titanic Sex: 577 male (64.8%), 314 female (35.2%). This imbalance means the model might default to predicting 'male' for accuracy but fail to identify female survivors.",
        python_example="```python\ndf['color'].value_counts()\ndf['color'].value_counts(normalize=True) * 100  # percentages\ndf['color'].value_counts().plot(kind='bar')\nprint(f'Unique values: {df[\"color\"].nunique()}')\n```",
        common_mistakes=["Not checking for rare categories (< 5% of data)", "Ignoring high-cardinality columns (500+ unique values)"],
        practice_exercise="How many unique values does each categorical column in Titanic have? Which has the most?",
        quiz=[
            QuizQuestion("A categorical column has 500 unique values. What problem does this create?", ["No problem", "One-hot encoding creates 500 new columns — sparse and slow", "The model will be more accurate", "You need more data"], 1, "High cardinality creates too many dummy columns, making models slow and sparse."),
        ],
        takeaways=["value_counts() shows distribution", "Check for rare categories", "High cardinality needs special handling"],
        lab_module="eda",
    ),
    Topic(id="eda_08", title="Histograms", section="eda", order=8, difficulty="beginner",
        objectives=["Create and interpret histograms", "Choose appropriate bin sizes", "Understand distribution shapes"],
        concept="A histogram divides data into bins and shows the frequency of values in each bin. It reveals the distribution shape: symmetric, skewed, bimodal, uniform.",
        why_matters="Distribution shape determines which models and transformations to use. Normal distributions suit linear models; skewed data needs transformation.",
        simple_explanation="A histogram is a bar chart of how often each value range appears.",
        example="Titanic Age histogram: peaks around 20-30 (young adults), fewer children and elderly. Not perfectly normal — slightly right-skewed with a gap around 5-10 years.",
        python_example="```python\ndf['age'].hist(bins=30, edgecolor='black', figsize=(8,5))\nimport matplotlib.pyplot as plt\nplt.xlabel('Age')\nplt.ylabel('Count')\nplt.title('Distribution of Age')\n```",
        common_mistakes=["Using too few bins (hides detail) or too many (shows noise)", "Not labelling axes", "Interpreting histograms of categorical data"],
        practice_exercise="Plot histograms of all numerical columns in Iris. Which feature is most symmetric?",
        quiz=[
            QuizQuestion("A histogram shows two separate peaks. What is this called?", ["Unimodal", "Bimodal", "Skewed", "Uniform"], 1, "Two peaks = bimodal distribution, suggesting two underlying groups."),
        ],
        takeaways=["Histograms show distribution shape", "Choose bin count carefully", "Shape guides model choice"],
        lab_module="eda",
    ),
    Topic(id="eda_09", title="Box Plots", section="eda", order=9, difficulty="beginner",
        objectives=["Create and read box plots", "Identify outliers using IQR", "Compare distributions across groups"],
        concept="A box plot shows the five-number summary (min, Q1, median, Q3, max) and flags outliers beyond 1.5×IQR. It's excellent for comparing distributions and spotting outliers.",
        why_matters="Box plots instantly reveal outliers and distribution spread, which directly impact model performance.",
        simple_explanation="The box = middle 50% of data. Whiskers = typical range. Dots beyond = outliers.",
        example="Titanic Fare box plot by Pclass: 1st class fares are higher and more spread out (many outliers), 2nd class is tighter, 3rd class is low and compact with a few high outliers.",
        python_example="```python\ndf.boxplot(column='age', by='survived')\nimport matplotlib.pyplot as plt\nplt.title('Age by Survival')\nplt.suptitle('')  # remove auto title\n```",
        common_mistakes=["Not grouping by a categorical variable when comparing", "Confusing box plot outliers with data errors"],
        practice_exercise="Create box plots of Fare grouped by Survival on Titanic. What do you observe?",
        quiz=[
            QuizQuestion("A dot beyond the whisker in a box plot represents:", ["The median", "An outlier", "A missing value", "The mode"], 1, "Dots beyond the whiskers (1.5×IQR) are statistical outliers."),
        ],
        takeaways=["Box plots show five-number summary + outliers", "Great for comparing groups", "Outliers = dots beyond whiskers"],
        lab_module="eda",
    ),
    Topic(id="eda_10", title="Bar Charts", section="eda", order=10, difficulty="beginner",
        objectives=["Create bar charts for categorical data", "Compare category frequencies", "Avoid common bar chart mistakes"],
        concept="Bar charts show the frequency or proportion of each category. They are the primary visualisation for categorical variables.",
        why_matters="Bar charts reveal class imbalance, rare categories, and distribution of categorical features.",
        simple_explanation="Bar charts answer: How many of each category do I have?",
        example="Titanic Pclass bar chart: 3rd class has 491 passengers (55%), 1st class 216 (24%), 2nd class 184 (21%). The dataset is imbalanced toward 3rd class.",
        python_example="```python\ndf['survived'].value_counts().plot(kind='bar')\ndf['survived'].value_counts(normalize=True).plot(kind='bar')\nplt.ylabel('Proportion')\nplt.title('Survival Distribution')\n```",
        common_mistakes=["Starting the y-axis at a non-zero value (misleading)", "Using bar charts for continuous data", "Not ordering categories logically"],
        practice_exercise="Create a bar chart of 'Pclass' on Titanic. Is the distribution balanced?",
        quiz=[
            QuizQuestion("When should you use a bar chart instead of a histogram?", ["For continuous numerical data", "For categorical data", "For time series", "For correlations"], 1, "Bar charts are for categorical data; histograms are for continuous numerical data."),
        ],
        takeaways=["Bar charts = categorical frequency", "Always start y-axis at zero", "Order categories logically"],
        lab_module="eda",
    ),
    Topic(id="eda_11", title="Scatter Plots", section="eda", order=11, difficulty="beginner",
        objectives=["Create scatter plots", "Identify linear/non-linear relationships", "Add colour for third variable"],
        concept="Scatter plots show the relationship between two numerical variables. The pattern reveals correlation, clustering, and outliers.",
        why_matters="Scatter plots reveal whether a linear model is appropriate, whether features are correlated, and whether outliers exist.",
        simple_explanation="Each dot is one observation. X = one feature, Y = another. Patterns in dots = relationships.",
        example="Titanic Age vs Fare scatter: Most passengers cluster at low fares (<50) across all ages. A few high-fare outliers exist at younger ages, suggesting wealthier young passengers.",
        python_example="```python\ndf.plot.scatter(x='age', y='fare', alpha=0.5)\n# With colour for a third variable\nplt.scatter(df['age'], df['fare'], c=df['survived'], cmap='coolwarm', alpha=0.5)\nplt.colorbar(label='Survived')\n```",
        common_mistakes=["Not using alpha for overlapping points", "Assuming correlation from visual pattern alone", "Not checking for clusters"],
        practice_exercise="Plot Age vs Fare on Titanic, coloured by Survival. What pattern do you see?",
        quiz=[
            QuizQuestion("Points in a scatter plot form a tight upward line. This indicates:", ["No correlation", "Strong positive correlation", "Strong negative correlation", "Random data"], 1, "Tight upward pattern = strong positive correlation (as X increases, Y increases)."),
        ],
        takeaways=["Scatter plots show relationships between two numerical variables", "Use alpha for overlapping points", "Pattern strength indicates correlation"],
        lab_module="eda",
    ),
    Topic(id="eda_12", title="Distribution Analysis", section="eda", order=12, difficulty="intermediate",
        objectives=["Identify distribution types", "Understand normal, skewed, bimodal distributions", "Choose appropriate transformations"],
        concept="Distribution analysis identifies the shape of data: normal (bell curve), right-skewed, left-skewed, bimodal (two peaks), uniform (flat). This guides model and transformation choices.",
        why_matters="Many models assume normally distributed features. Skewed data needs transformation. Bimodal data suggests hidden subgroups.",
        simple_explanation="The shape of your data's distribution determines which tools and models will work best.",
        example="Titanic Fare is right-skewed (most fares low, few very high). After log transformation, it becomes approximately symmetric — better for linear models.",
        python_example="```python\nfrom scipy import stats\nimport matplotlib.pyplot as plt\n\n# KDE plot\ndf['age'].plot(kind='kde')\n\n# Test for normality\nstat, p = stats.shapiro(df['age'].dropna())\nprint(f'Shapiro-Wilk p-value: {p:.4f}')\nif p > 0.05:\n    print('Likely normal')\nelse:\n    print('Not normal')\n```",
        common_mistakes=["Assuming all data is normally distributed", "Not testing for normality before using normal-based methods"],
        practice_exercise="Test if the 'Age' column in Titanic follows a normal distribution. What do you find?",
        quiz=[
            QuizQuestion("A Shapiro-Wilk test returns p=0.001. What does this mean?", ["The data is normally distributed", "The data is NOT normally distributed", "The test failed", "The data is skewed right"], 1, "p < 0.05 rejects the null hypothesis of normality — the data is not normal."),
        ],
        takeaways=["Distribution shape guides model choice", "Normality tests help verify assumptions", "Skewed data often needs log transformation"],
        lab_module="eda",
    ),
    Topic(id="eda_13", title="Outlier Detection", section="eda", order=13, difficulty="intermediate",
        objectives=["Identify outliers visually and statistically", "Use IQR and Z-score methods", "Decide how to handle outliers"],
        concept="Outliers are extreme values far from the majority. Detect with box plots (IQR method) or Z-scores (values > 3 standard deviations).",
        why_matters="Outliers distort means, correlations, and model training. Some models (linear regression, KNN) are very sensitive to them.",
        simple_explanation="Outliers are data points that are unusually far from the rest. They may be errors or genuine extremes.",
        example="Titanic Fare: Q1=7.9, Q3=31.0, IQR=23.1. Upper fence = 31.0 + 1.5×23.1 = 65.7. Fares above 65.7 are outliers — includes the 512.3 first-class ticket.",
        python_example="```python\n# IQR method\nQ1 = df['fare'].quantile(0.25)\nQ3 = df['fare'].quantile(0.75)\nIQR = Q3 - Q1\noutliers = df[(df['fare'] < Q1 - 1.5*IQR) | (df['fare'] > Q3 + 1.5*IQR)]\nprint(f'{len(outliers)} outliers found')\n\n# Z-score\nfrom scipy import stats\nz_scores = stats.zscore(df['fare'].dropna())\noutliers = abs(z_scores) > 3\n```",
        common_mistakes=["Removing all outliers without investigation", "Not distinguishing errors from genuine extremes", "Using Z-score on non-normal data"],
        practice_exercise="Find outliers in the 'Fare' column of Titanic using the IQR method. How many are there?",
        quiz=[
            QuizQuestion("You find 5 outliers in a 1000-row dataset. What should you do first?", ["Remove all 5", "Investigate whether they're errors or genuine", "Cap them all at Q3", "Ignore them"], 1, "Always investigate first. Genuine outliers (e.g., very expensive houses) should be kept or transformed, not removed."),
        ],
        takeaways=["Outliers = extreme values", "IQR method: beyond Q1-1.5*IQR or Q3+1.5*IQR", "Always investigate before removing"],
        lab_module="eda",
    ),
    Topic(id="eda_14", title="Correlation", section="eda", order=14, difficulty="intermediate",
        objectives=["Compute Pearson and Spearman correlation", "Interpret correlation coefficients", "Distinguish correlation from causation"],
        concept="Correlation measures the linear relationship between two variables. Pearson (range: -1 to 1) measures linear correlation. Spearman measures monotonic correlation.",
        why_matters="High correlation between features (multicollinearity) confuses models. Correlation with the target identifies useful features.",
        simple_explanation="Correlation = how two variables move together. +1 = same direction, -1 = opposite direction, 0 = no linear relationship.",
        example="Titanic: Pclass and Fare have correlation -0.55 (higher class = lower fare, which makes sense). Survived and Pclass have correlation -0.34 (higher class = more likely survived).",
        python_example="```python\n# Pearson correlation\ndf[['age', 'fare']].corr()\n\n# Spearman (non-linear)\ndf[['age', 'fare']].corr(method='spearman')\n\n# Correlation with target\ndf.corr()['survived'].sort_values(ascending=False)\n```",
        common_mistakes=["Confusing correlation with causation", "Using Pearson for non-linear relationships", "Ignoring that correlation can be spurious"],
        practice_exercise="Compute the correlation matrix of Iris. Which two features are most strongly correlated?",
        quiz=[
            QuizQuestion("A correlation of -0.85 between two features means:", ["Strong positive relationship", "Strong negative relationship", "No relationship", "Perfect positive relationship"], 1, "Negative correlation means as one increases, the other decreases. -0.85 is strong."),
        ],
        takeaways=["Correlation ranges from -1 to +1", "Pearson = linear, Spearman = monotonic", "Correlation ≠ causation"],
        lab_module="eda",
    ),
    Topic(id="eda_15", title="Correlation Matrix", section="eda", order=15, difficulty="intermediate",
        objectives=["Create correlation heatmaps", "Identify multicollinearity", "Read a correlation matrix"],
        concept="A correlation matrix shows correlation coefficients between all pairs of numerical features. Visualised as a heatmap, it reveals the overall relationship structure.",
        why_matters="Multicollinearity (features highly correlated with each other) hurts linear models and makes feature importance unreliable.",
        simple_explanation="A correlation matrix is a table of how every numerical feature relates to every other.",
        example="California Housing heatmap: 'total_rooms' and 'total_bedrooms' correlate 0.93 (multicollinearity). 'median_income' correlates 0.69 with 'median_house_value' (useful predictor).",
        python_example="```python\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\ncorr = df.select_dtypes('number').corr()\nplt.figure(figsize=(10,8))\nsns.heatmap(corr, annot=True, cmap='coolwarm', center=0)\nplt.title('Correlation Matrix')\nplt.tight_layout()\nplt.show()\n```",
        common_mistakes=["Not using a colour scale centred at 0", "Ignoring off-diagonal high correlations", "Including the target in feature correlation checks"],
        practice_exercise="Create a correlation heatmap for California Housing. Which features are most correlated with median_house_value?",
        quiz=[
            QuizQuestion("In a correlation heatmap, a dark red square between two features indicates:", ["Strong negative correlation", "Strong positive correlation", "No correlation", "Missing data"], 1, "Red in a coolwarm palette = positive correlation. Dark red = strong positive."),
        ],
        takeaways=["Correlation matrix = all pairwise correlations", "High off-diagonal values = multicollinearity", "Use heatmap for visual inspection"],
        lab_module="eda",
    ),
    Topic(id="eda_16", title="Missing-Value Analysis", section="eda", order=16, difficulty="intermediate",
        objectives=["Visualise missing data patterns", "Distinguish MCAR/MAR/MNAR", "Decide on imputation strategy"],
        concept="Missing-value analysis in EDA goes beyond counting — it examines patterns: Is missingness random? Does it correlate with other features? This determines the best imputation strategy.",
        why_matters="The missingness mechanism (MCAR/MAR/MNAR) determines which imputation method is appropriate. Wrong imputation biases results.",
        simple_explanation="Are values missing randomly (lucky), because of other features (predictable), or because of the value itself (systematic)?",
        example="Titanic: Age is missing more for 3rd class passengers (MAR — missingness relates to passenger class). Cabin is missing for most passengers (MNAR — only those with cabins have them recorded).",
        python_example="```python\n# Missing value heatmap\nimport seaborn as sns\nsns.heatmap(df.isnull(), cbar=True, yticklabels=False)\nplt.title('Missing Data Pattern')\n\n# Correlation of missingness\ndf_missing = df.isnull().astype(int)\ndf_missing.corr()\n```",
        common_mistakes=["Assuming all missing data is random", "Not checking if missingness correlates with the target", "Using mean imputation when data is not MCAR"],
        practice_exercise="Create a missing-value heatmap for Titanic. Does missingness in Age correlate with any other feature?",
        quiz=[
            QuizQuestion("Missing values in 'Income' are more common for older people. This is:", ["MCAR (Missing Completely at Random)", "MAR (Missing at Random)", "MNAR (Missing Not at Random)", "Cannot determine"], 1, "Missingness depends on Age (another observed variable), so it's MAR."),
        ],
        takeaways=["Visualise missing patterns with heatmaps", "MCAR/MAR/MNAR determines imputation strategy", "Check if missingness correlates with other features"],
        lab_module="eda",
    ),
    Topic(id="eda_17", title="Identifying Patterns", section="eda", order=17, difficulty="intermediate",
        objectives=["Recognise data patterns", "Identify trends and seasonality", "Spot structural breaks"],
        concept="Pattern identification looks for trends (increasing/decreasing over time), seasonality (regular cycles), clusters (groups of similar observations), and structural breaks (sudden changes).",
        why_matters="Patterns guide feature engineering and model choice. Time trends need temporal features. Clusters suggest segmentation.",
        simple_explanation="Data often has hidden structure — trends, cycles, groups. Finding them unlocks better models.",
        example="California Housing: Homes near the coast (low latitude, high longitude) have higher prices. This geographic pattern suggests latitude/longitude as important features.",
        python_example="```python\n# Time series trend\ndf.plot(x='date', y='value')\n\n# Clusters in features\nfrom sklearn.cluster import KMeans\nkmeans = KMeans(n_clusters=3)\ndf['cluster'] = kmeans.fit_predict(df[['feature1', 'feature2']])\n```",
        common_mistakes=["Confusing correlation with trends", "Not accounting for seasonality in time series", "Ignoring clusters that represent real subgroups"],
        practice_exercise="Plot the Age distribution on Titanic, split by Survival. What pattern do you see?",
        quiz=[
            QuizQuestion("You notice that 'Purchase Amount' increases every December. This is:", ["A trend", "Seasonality", "An outlier", "Missing data"], 1, "Regular annual pattern (December spike) = seasonality."),
        ],
        takeaways=["Patterns include trends, seasonality, and clusters", "Visualise by groups to find hidden structure", "Patterns guide feature engineering"],
        lab_module="eda",
    ),
    Topic(id="eda_18", title="Visualization Best Practices", section="eda", order=18, difficulty="intermediate",
        objectives=["Choose the right chart type", "Apply Tufte's principles", "Create clear, honest visualisations"],
        concept="Good visualisation communicates clearly. Choose charts based on data type: bar for categories, histogram for distributions, scatter for relationships, line for time series.",
        why_matters="A misleading visualisation can lead to wrong conclusions. Clear visualisation is essential for communicating findings.",
        simple_explanation="The right chart for the right data tells a story. The wrong chart tells a lie.",
        example="Comparing survival rates: A bar chart starting at 0 shows the true difference (74% vs 19%). Starting at 15% makes the gap look 3× larger than it is.",
        python_example="```python\nimport matplotlib.pyplot as plt\n\n# GOOD: Bar chart starting at 0\nfig, axes = plt.subplots(1, 2, figsize=(10, 4))\naxes[0].bar(['Male', 'Female'], [19, 74])\naxes[0].set_ylim(0, 100)\naxes[0].set_title('Honest Scale')\n\n# BAD: Truncated axis\naxes[1].bar(['Male', 'Female'], [19, 74])\naxes[1].set_ylim(15, 80)\naxes[1].set_title('Misleading Scale')\n```",
        common_mistakes=["Using pie charts for too many categories", "Truncating axes to exaggerate differences", "Using 3D charts that distort perception", "Not labelling axes"],
        practice_exercise="Redesign a poorly made chart. What principles did you apply?",
        quiz=[
            QuizQuestion("Which chart is best for showing proportions of a whole with fewer than 6 categories?", ["Line chart", "Scatter plot", "Pie chart or bar chart", "Histogram"], 2, "Pie charts and bar charts show proportions. Pie is best for <6 categories."),
        ],
        takeaways=["Match chart to data type", "Label everything", "Avoid misleading scales"],
        lab_module="eda",
    ),
    Topic(id="eda_19", title="Misleading Visualisations", section="eda", order=19, difficulty="intermediate",
        objectives=["Identify common misleading techniques", "Understand how charts can deceive", "Practice honest data presentation"],
        concept="Visualisations can mislead through: truncated y-axes, cherry-picked data, inappropriate chart types, and suppressed context. Recognising these protects you from bad conclusions.",
        why_matters="Misleading charts are used in media and business to distort reality. As a data scientist, you must recognise and avoid them.",
        simple_explanation="A chart can lie just as easily as words. Learn to spot the tricks.",
        example="A news headline 'Housing prices doubled!' uses a chart from 2010-2020 (post-recovery boom). Showing 2000-2020 reveals prices actually fell during 2008-2012, making the 'doubling' less impressive over 20 years.",
        python_example="```python\n# MISLEADING: truncated y-axis makes difference look huge\nplt.ylim(90, 100)  # don't do this!\n\n# CORRECT: start from zero\nplt.ylim(0, 100)\n\n# MISLEADING: cherry-picking time range\n# CORRECT: show full context\n```",
        common_mistakes=["Truncating axes to exaggerate differences", "Showing only a subset of data that supports a conclusion", "Using area/volume charts where bar charts are clearer"],
        practice_exercise="Find an example of a misleading chart online. What makes it misleading?",
        quiz=[
            QuizQuestion("A bar chart of test scores starts the y-axis at 85 instead of 0. This is:", ["Good practice", "Misleading — exaggerates differences", "Required for test scores", "Standard in statistics"], 1, "Starting at 85 makes 2-point differences look huge. Always start bar chart axes at zero."),
        ],
        takeaways=["Truncated axes exaggerate differences", "Cherry-picking hides context", "Always start bar charts at zero"],
        lab_module="eda",
    ),
    Topic(id="eda_20", title="EDA Case Study", section="eda", order=20, difficulty="advanced",
        objectives=["Apply all EDA techniques to a real dataset", "Document findings", "Connect EDA insights to modelling decisions"],
        concept="An EDA case study applies all techniques systematically: load → quality check → univariate → bivariate → multivariate → visualise → document findings → decide next steps.",
        why_matters="Real-world EDA is an iterative process. This case study shows how techniques combine to form a complete analysis.",
        simple_explanation="Put it all together: load data, check quality, explore distributions, find relationships, and document what you learned.",
        example="Titanic case study: Missing Age (19.8%) → Embarked (0.2%). Fare is right-skewed. Females had higher survival. Pclass correlated with survival. Age younger → more likely survived.",
        python_example="```python\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Load and check\ndf = pd.read_csv('titanic.csv')\nprint(f'Shape: {df.shape}')\nprint(f'\\nMissing:\\n{df.isnull().sum()}')\n\n# Univariate\nprint(df.describe())\ndf['Age'].hist(bins=30)\n\n# Bivariate\nprint(df.groupby('Sex')['Survived'].mean())\nprint(df.groupby('Pclass')['Survived'].mean())\n\n# Multivariate\nsns.heatmap(df.select_dtypes('number').corr(), annot=True)\nplt.show()\n```",
        common_mistakes=["Not documenting findings", "Jumping to conclusions without statistical support", "Stopping EDA too early"],
        practice_exercise="Perform a complete EDA on the California Housing dataset. Write a one-page summary of your findings.",
        quiz=[
            QuizQuestion("What is the LAST step of a systematic EDA?", ["Load data", "Plot histograms", "Document findings and decide next steps", "Train a model"], 2, "EDA ends with documentation — recording findings and deciding what preprocessing/modeling to do next."),
        ],
        takeaways=["EDA is systematic: load → check → explore → document → decide", "Always document findings", "EDA insights guide all modelling decisions"],
        lab_module="eda",
    ),
]
