"""Feature Engineering curriculum — 22 topics."""

from learning import QuizQuestion, Topic

TOPICS = [
    Topic(
        id="fe_01", title="What is Feature Engineering?", section="feature_engineering", order=1, difficulty="beginner",
        objectives=["Define feature engineering", "Understand its role in the ML pipeline", "Recognise why raw features are often insufficient"],
        concept="Feature engineering is the process of using domain knowledge to create new input variables (features) from existing data, or to transform existing features to better represent the underlying problem to a machine learning model.",
        why_matters="The quality of your features directly determines model performance. A well-engineered feature can improve accuracy more than switching algorithms. As Andrew Ng said: 'Applied ML is basically feature engineering.'",
        simple_explanation="Imagine you have a 'date' column. The model can't understand dates directly. Feature engineering turns it into 'is_weekend', 'month', 'day_of_year' — numbers the model can use.",
        example="In the Titanic dataset, raw columns include 'Name' and 'SibSp' + 'Parch'. Feature engineering creates 'Title' (Mr, Mrs, Miss) from Name and 'FamilySize' = SibSp + Parch + 1.",
        python_example="```python\nimport pandas as pd\nimport numpy as np\n\ndf['family_size'] = df['SibSp'] + df['Parch'] + 1\ndf['title'] = df['Name'].str.extract(r' ([A-Za-z]+)\\.')\\ndf['is_alone'] = (df['family_size'] == 1).astype(int)\n```",
        interpretation="New features capture information that raw data obscures. 'FamilySize' tells the model about group dynamics that two separate columns cannot.",
        common_mistakes=[
            "Creating too many features without testing their value (curse of dimensionality)",
            "Using information that won't be available at prediction time (target leakage)",
            "Not checking if the new feature actually improves the model",
        ],
        practice_exercise="Load the Titanic dataset. Create three new features: FamilySize, IsAlone, and Title (extracted from Name). Which do you think will be most predictive of survival?",
        quiz=[
            QuizQuestion(
                "Feature engineering is most important for which reason?",
                ["It makes the code run faster", "It creates features that help models learn patterns more easily", "It reduces the number of rows", "It removes missing values"], 1, "Good features encode domain knowledge, making it easier for models to find patterns."
            ),
        ],
        takeaways=["Feature engineering creates new, informative inputs from raw data", "Domain knowledge drives good feature creation", "Always test whether new features actually improve performance"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_02", title="Why Features Matter", section="feature_engineering", order=2, difficulty="beginner",
        objectives=["Understand the relationship between feature quality and model performance", "Recognise that better features beat better algorithms", "Appreciate the effort-to-reward ratio of feature engineering"],
        concept="Models learn patterns in features. If features don't capture the relevant information, no model — no matter how sophisticated — can learn it. The ceiling of model performance is set by feature quality.",
        why_matters="Research consistently shows that feature engineering has a higher return on investment than algorithm tuning. A simple model with great features often outperforms a complex model with poor features.",
        simple_explanation="A model is only as smart as its inputs. If you show it raw pixels, it struggles. If you show it 'edge count' and 'colour histogram', it thrives.",
        example="Predicting house prices: raw features might be 'address' and 'year_built'. Engineered features: 'price_per_sqft_neighbourhood', 'house_age', 'is_recently_renovated' — these directly relate to price.",
        python_example="```python\nimport pandas as pd\nimport numpy as np\n\n# Raw features vs engineered features\ndf['house_age'] = 2024 - df['year_built']\ndf['price_per_sqft'] = df['price'] / df['sqft']\ndf['is_renovated'] = (df['year_renovated'] > 0).astype(int)\n\n# Compare model performance with and without engineered features\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import cross_val_score\n\nscore_raw = cross_val_score(model, X_raw, y, cv=5).mean()\nscore_engineered = cross_val_score(model, X_engineered, y, cv=5).mean()\nprint(f'Raw: {score_raw:.3f}, Engineered: {score_engineered:.3f}')\n```",
        common_mistakes=[
            "Spending all time tuning hyperparameters instead of improving features",
            "Not brainstorming features with domain experts",
            "Creating features that leak the target variable",
        ],
        practice_exercise="Take the California Housing dataset. Create 3 engineered features (e.g., rooms_per_household, bedrooms_ratio, income_category). Measure if they improve a Random Forest.",
        quiz=[
            QuizQuestion("Why do better features often beat better algorithms?", ["Algorithms don't matter", "Features encode the patterns models need to learn", "Better features reduce training time", "Features eliminate the need for preprocessing"], 1, "Features encode the signal that models learn from. Without good features, even the best algorithm cannot find patterns."),
            QuizQuestion("What is the biggest risk of feature engineering?", ["Overfitting the training data", "Creating features that leak the target variable", "Making the code too slow", "Using too many libraries"], 1, "Target leakage is the most dangerous — features that accidentally include information from the target variable give unrealistic performance."),
        ],
        takeaways=["Better features > better algorithms in most cases", "Feature engineering requires domain knowledge", "The best feature engineering is testing, not guessing"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_03", title="Feature Creation", section="feature_engineering", order=3, difficulty="beginner",
        objectives=["Create new features from existing ones", "Understand ratios, differences, and aggregations", "Apply domain logic to create meaningful variables"],
        concept="Feature creation combines or derives new columns from existing ones. Common operations: ratios (price/area), differences (current_year - build_year), counts (family_size), and aggregations (average purchase per customer).",
        why_matters="Raw features often hide the most important signal. A ratio of two features can be more predictive than either feature alone.",
        simple_explanation="If you have height and width, create area (height × width). If you have start_date and end_date, create duration (end - start).",
        example="Titanic: SibSp (siblings/spouses) and Parch (parents/children) are weak individually. But FamilySize = SibSp + Parch + 1 captures whether passengers travelled alone or in groups — a much stronger signal.",
        python_example="```python\n# Ratio features\ndf['price_per_sqft'] = df['price'] / df['sqft']\n\n# Difference features\ndf['house_age'] = 2024 - df['year_built']\n\n# Count features\ndf['family_size'] = df['sibsp'] + df['parch'] + 1\n\n# Flag features\ndf['has_garage'] = (df['garage_area'] > 0).astype(int)\n```",
        common_mistakes=[
            "Creating division features without checking for zero denominators",
            "Creating features that combine unrelated columns",
            "Not normalising ratio features when scales differ greatly",
        ],
        practice_exercise="Create these features on Titanic: IsAlone (FamilySize == 1), FarePerPerson (Fare / FamilySize), AgeGroup (bins). Test which improves survival prediction.",
        quiz=[
            QuizQuestion("When creating a ratio feature like price/area, what must you check first?", ["If the area column exists", "If area has any zero values", "If price is normally distributed", "If the data is sorted"], 1, "Division by zero creates infinite values that crash models. Always check for zeros before dividing."),
            QuizQuestion("FamilySize = SibSp + Parch + 1. Why add 1?", ["To include the passenger themselves", "To avoid zero values", "For rounding", "Because pandas requires it"], 0, "The +1 accounts for the passenger — SibSp and Parch only count family members, not the individual."),
        ],
        takeaways=["Ratios, differences, and counts are the most common created features", "Always check for division by zero", "Flag features (0/1) are simple and often powerful"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_04", title="Feature Transformation", section="feature_engineering", order=4, difficulty="beginner",
        objectives=["Apply mathematical transformations to features", "Understand when transformations help", "Choose appropriate transformations based on distribution"],
        concept="Feature transformation changes the distribution or scale of a feature without changing its rank order. Common transformations: log, square root, reciprocal, power. These help when data is skewed or has wide ranges.",
        why_matters="Many models assume approximately normal distributions. Skewed features violate this assumption and reduce model performance. Transformations fix this.",
        simple_explanation="Transformations reshape your data. A log transformation takes a right-skewed distribution (like income) and makes it more symmetric.",
        example="Income data: $20K, $25K, $30K, $50K, $100K, $1M. The mean is misleadingly high. After log: 9.9, 10.1, 10.3, 10.8, 11.5, 13.8 — much more symmetric.",
        python_example="```python\nimport numpy as np\nimport matplotlib.pyplot as plt\n\n# Before transformation\nplt.hist(df['income'], bins=30)\nplt.title('Income: Right-Skewed')\n\n# After log transformation\ndf['log_income'] = np.log1p(df['income'])\nplt.hist(df['log_income'], bins=30)\nplt.title('Log(Income): More Symmetric')\n\n# Compare skewness\nprint(f'Original skewness: {df[\"income\"].skew():.2f}')\nprint(f'After log: {df[\"log_income\"].skew():.2f}')\n```",
        common_mistakes=[
            "Applying log to zero or negative values without handling them first",
            "Transforming the target variable without accounting for the inverse transformation in predictions",
            "Not checking if the transformation actually helped",
        ],
        practice_exercise="Apply log transformation to California Housing's 'median_income'. Plot before and after histograms. Did skewness improve?",
        quiz=[
            QuizQuestion("Why do we transform features before modelling?", ["To make the code faster", "To make distributions more symmetric and scale-appropriate", "To add more rows", "To remove missing values"], 1, "Transformations fix skewness and scale issues that violate model assumptions."),
            QuizQuestion("Which transformation is best for right-skewed income data?", ["Square root", "Log transformation", "StandardScaler only", "No transformation needed"], 1, "Log transformation compresses right skew, making income distributions more symmetric."),
        ],
        takeaways=["Transformations fix skewed distributions", "Log is the most common transformation for right-skewed data", "Always check before and after distributions"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_05", title="Mathematical Transformations", section="feature_engineering", order=5, difficulty="beginner",
        objectives=["Apply log, sqrt, and square transformations", "Understand when each is appropriate", "Handle edge cases (zero, negative values)"],
        concept="Each mathematical function reshapes data differently:\n- **Log**: Compresses right skew, spreads out left values. Use for income, prices, counts.\n- **Square root**: Mild compression. Use for count data (Poisson-like).\n- **Square**: Expands large values. Rarely used but can highlight extremes.",
        why_matters="The right transformation can be the difference between a model that captures a pattern and one that misses it entirely.",
        example="Website visits: 0, 1, 3, 5, 12, 45, 200. Log: NaN, 0, 1.4, 1.8, 2.6, 3.8, 5.3. Sqrt: 0, 1, 1.7, 2.2, 3.5, 6.7, 14.1. Log compresses more aggressively.",
        python_example="```python\nimport numpy as np\n\n# Log transformation (use log1p for zeros)\ndf['log_income'] = np.log1p(df['income'])\n\n# Square root (handles zeros natively)\ndf['sqrt_count'] = np.sqrt(df['count'])\n\n# Square (rarely used, highlights extremes)\ndf['sq_distance'] = df['distance'] ** 2\n```",
        interpretation="After log transformation, a one-unit increase in the transformed feature corresponds to a multiplicative change in the original. This is useful for modelling percentage changes.",
        common_mistakes=[
            "Using np.log() on data with zeros — use np.log1p() instead",
            "Forgetting to reverse the transformation for predictions",
            "Applying transformations to features that are already symmetric",
        ],
        practice_exercise="Apply all three transformations to California Housing's 'population' column. Which produces the most symmetric distribution?",
        quiz=[
            QuizQuestion("np.log1p(x) is preferred over np.log(x) because:", ["It's faster", "It handles zeros safely by computing log(1+x)", "It produces integers", "It works on strings"], 1, "log1p computes log(1+x), so log(1+0) = log(1) = 0 instead of undefined."),
            QuizQuestion("Square root transformation is best suited for:", ["Income data", "Count data following Poisson distribution", "Binary features", "Text lengths"], 1, "Square root stabilises variance for count data, which often follows a Poisson-like distribution."),
        ],
        takeaways=["np.log1p handles zeros safely", "Log transformation is for right-skewed data", "Square root is for mild compression of count data"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_06", title="Log Transformation", section="feature_engineering", order=6, difficulty="beginner",
        objectives=["Apply log transformation correctly", "Understand the mathematical effect", "Interpret model coefficients after log transformation"],
        concept="The log transformation converts multiplicative relationships into additive ones. If y = log(x), then a unit change in y corresponds to a percentage change in x. This is why log-transformed coefficients can be interpreted as elasticities.",
        why_matters="Income, prices, population, and many real-world variables follow log-normal distributions. Log transformation makes them suitable for linear models.",
        example="House prices: $100K, $150K, $200K, $500K, $1M. After log: 11.5, 11.9, 12.2, 13.1, 13.8. A 1-unit increase in log-price ≈ 2.7× increase in actual price (e^1 ≈ 2.718).",
        python_example="```python\nimport numpy as np\nimport matplotlib.pyplot as plt\n\n# Before transformation\nplt.hist(df['income'], bins=30)  # right-skewed\nplt.title('Income: Right-Skewed')\n\n# After transformation\ndf['log_income'] = np.log1p(df['income'])\nplt.hist(df['log_income'], bins=30)  # approximately symmetric\nplt.title('Log(Income): Symmetric')\n```",
        interpretation="In a linear model with log-transformed target: a 1-unit increase in a feature → e^coefficient % increase in the original target. For example, coefficient 0.05 → ~5% increase.",
        common_mistakes=[
            "Applying log to negative values (log of negative is undefined)",
            "Forgetting np.log1p() which handles zeros (log(1+x) instead of log(x))",
            "Not reversing the transformation: predictions need exp(pred) - 1",
        ],
        practice_exercise="Log-transform California Housing's 'median_house_value'. Fit a linear regression and interpret the coefficients as percentage changes.",
        quiz=[
            QuizQuestion("If a linear model has coefficient 0.1 for a log-transformed feature, what does it mean?", ["10% increase in the feature", "10% increase in the original target per unit increase", "0.1 unit increase in target", "The feature is unimportant"], 1, "With log transformation, coefficient 0.1 ≈ 10% increase in the original (untransformed) target."),
            QuizQuestion("To reverse a log transformation on predictions, you use:", ["log(pred)", "exp(pred)", "exp(pred) - 1", "pred ** 2"], 2, "Since we used log1p (log(1+x)), the inverse is exp(pred) - 1."),
        ],
        takeaways=["Log transforms right-skewed data into symmetric", "Use np.log1p() for safety with zeros", "Remember to reverse for predictions"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_07", title="Square Root Transformation", section="feature_engineering", order=7, difficulty="beginner",
        objectives=["Apply sqrt transformation", "Know when sqrt is better than log", "Handle zero values"],
        concept="The square root transformation compresses right skewness more gently than log. It naturally handles zeros and is ideal for count data that follows a Poisson distribution.",
        why_matters="Count data (number of children, items sold, website visits) often follows Poisson-like distributions where sqrt stabilises variance.",
        example="Website visits: [0, 1, 3, 5, 12, 45, 200]. Sqrt: [0, 1, 1.7, 2.2, 3.5, 6.7, 14.1]. The compression is gentler than log, preserving more of the original scale.",
        python_example="```python\nimport numpy as np\n\ndf['sqrt_visits'] = np.sqrt(df['visits'])\n# np.sqrt handles zeros natively, unlike np.log\n\n# Compare distributions\nprint(f'Original skewness: {df[\"visits\"].skew():.2f}')\nprint(f'After sqrt: {df[\"sqrt_visits\"].skew():.2f}')\n```",
        common_mistakes=[
            "Using sqrt on negative values (returns NaN)",
            "Using sqrt when log would be more appropriate (extreme skewness)",
        ],
        practice_exercise="Compare log and sqrt transformations on California Housing's 'population' column. Which reduces skewness more?",
        quiz=[
            QuizQuestion("Square root transformation is gentler than log transformation because:", ["It compresses values less aggressively", "It's faster to compute", "It handles negative values", "It's more interpretable"], 0, "Sqrt compresses right skew more gently, preserving more of the original scale than log."),
            QuizQuestion("When is sqrt transformation preferred over log?", ["When data is extremely right-skewed", "When data is count data with zeros", "When data is normally distributed", "When data has negative values"], 1, "Sqrt handles zeros natively and provides gentle compression ideal for count data."),
        ],
        takeaways=["sqrt is gentler than log for right skew", "Handles zeros naturally", "Best for count data (Poisson-like)"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_08", title="Polynomial Features", section="feature_engineering", order=8, difficulty="intermediate",
        objectives=["Generate polynomial and interaction features", "Understand the bias-variance tradeoff", "Choose appropriate polynomial degree"],
        concept="Polynomial features create x², x³, and interaction terms (x₁×x₂) to capture non-linear relationships. A linear model with polynomial features can fit curved patterns.",
        why_matters="Linear models can only learn linear relationships. Polynomial features let linear models capture curves, without switching to a more complex algorithm.",
        example="If age alone has a non-linear relationship with survival (very young and very old had lower survival), adding age² lets a linear model capture this U-shaped pattern.",
        python_example="```python\nfrom sklearn.preprocessing import PolynomialFeatures\n\n# degree=2: creates x1, x2, x1², x1*x2, x2²\npoly = PolynomialFeatures(degree=2, include_bias=False)\npoly_features = poly.fit_transform(df[['feature1', 'feature2']])\nprint(poly.get_feature_names_out())\n# ['feature1', 'feature2', 'feature1^2', 'feature1 feature2', 'feature2^2']\n```",
        interpretation="Degree 2 adds quadratic terms and pairwise interactions. Degree 3 adds cubic terms — but the number of features grows exponentially, risking overfitting.",
        common_mistakes=[
            "Using degree > 3 (features explode exponentially, causing overfitting)",
            "Not scaling features before polynomial expansion (very large values)",
            "Including bias term when the model already has an intercept",
        ],
        practice_exercise="Apply PolynomialFeatures(degree=2) to California Housing's 'median_income' and 'rooms'. How many features are created?",
        quiz=[
            QuizQuestion("PolynomialFeatures(degree=2) on 2 features creates how many output features?", ["2", "4", "5", "6"], 2, "degree=2 creates: x1, x2, x1², x1*x2, x2² = 5 features (with include_bias=False)."),
            QuizQuestion("Why should you scale features before polynomial expansion?", ["Scaling is always required", "Polynomial terms amplify differences in scale", "To reduce computation time", "To prevent NaN values"], 1, "Squaring a feature with range 0-1000 produces values up to 1,000,000 — scaling first keeps values manageable."),
        ],
        takeaways=["Polynomial features capture non-linear relationships", "Keep degree ≤ 2 for most cases", "Always scale features first"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_09", title="Interaction Features", section="feature_engineering", order=9, difficulty="intermediate",
        objectives=["Create interaction features between columns", "Understand when interactions matter", "Interpret interaction effects"],
        concept="An interaction feature combines two features (usually by multiplication) to capture their joint effect. If height and width individually predict area, height×width captures their combined effect.",
        why_matters="Some effects only appear when two features are considered together. For example, the effect of study hours on exam score depends on prior knowledge — the interaction captures this.",
        example="Titanic: Age alone has weak correlation with Survival (r=0.07). But Age×Pclass interaction captures that young 1st-class passengers survived at much higher rates than young 3rd-class passengers.",
        python_example="```python\n# Manual interaction\ndf['age_x_income'] = df['age'] * df['income']\n\n# Using PolynomialFeatures (degree=2, interaction_only=True)\nfrom sklearn.preprocessing import PolynomialFeatures\npoly = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)\ninteractions = poly.fit_transform(df[['age', 'income']])\n# Creates: age, income, age*income\n```",
        common_mistakes=[
            "Creating interactions between all feature pairs (combinatorial explosion)",
            "Not checking if the interaction is actually meaningful",
            "Forgetting to scale features before creating interaction terms",
        ],
        practice_exercise="Create an interaction feature between 'median_income' and 'rooms' in California Housing. Does it improve model performance?",
        quiz=[
            QuizQuestion("An interaction feature A×B is useful when:", ["A and B are highly correlated", "The effect of A on the target depends on B", "Both A and B are categorical", "The dataset is small"], 1, "Interaction effects capture when one variable's impact on the target changes based on another variable's value."),
            QuizQuestion("PolynomialFeatures with interaction_only=True creates:", ["Only squared terms", "Only cross-product terms", "Both squared and cross-product", "No new features"], 1, "interaction_only=True skips the squared terms (x1², x2²) and creates only the cross-product (x1*x2)."),
        ],
        takeaways=["Interaction features capture joint effects of two variables", "Use domain knowledge to choose which interactions to create", "Interaction-only PolynomialFeatures avoids squared terms"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_10", title="Binning", section="feature_engineering", order=10, difficulty="intermediate",
        objectives=["Bin continuous variables into categories", "Choose between equal-width and quantile binning", "Understand trade-offs of binning"],
        concept="Binning (discretisation) converts continuous variables into discrete bins. Equal-width: bins have same range. Quantile: bins have same number of observations. Binning captures non-linear effects and reduces outlier influence.",
        why_matters="Binning can capture non-linear relationships that linear models miss. For example, age groups (child/teen/adult/senior) may predict better than raw age.",
        example="Titanic Age: Equal-width bins [0-16, 16-32, 32-48, 48-64, 64-80] put most passengers in the middle bins. Quantile bins ensure equal counts per group, making each group comparable.",
        python_example="```python\nimport pandas as pd\n\n# Equal-width binning (5 bins)\ndf['age_group'] = pd.cut(df['age'], bins=5,\n    labels=['Very Young', 'Young', 'Middle', 'Senior', 'Elderly'])\n\n# Quantile binning (equal frequency)\ndf['fare_quartile'] = pd.qcut(df['fare'], q=4,\n    labels=['Low', 'Medium', 'High', 'Very High'])\n\n# Custom bins\ndf['age_custom'] = pd.cut(df['age'], bins=[0, 18, 65, 100],\n    labels=['Child', 'Adult', 'Senior'])\n```",
        interpretation="Equal-width may create unbalanced bins if data is skewed. Quantile ensures equal frequency but may put very different values in the same bin.",
        common_mistakes=[
            "Using too many bins (loses the benefit of binning)",
            "Using equal-width on skewed data (most data ends up in one bin)",
            "Losing ordinal information when binning creates nominal categories",
        ],
        practice_exercise="Bin California Housing's 'median_income' into 4 equal-width groups and 4 quantile groups. How do the distributions differ?",
        quiz=[
            QuizQuestion("Equal-width binning on right-skewed data typically produces:", ["Balanced bins", "Most data in one bin with others nearly empty", "Exactly equal counts per bin", "No change in distribution"], 1, "Right-skewed data has most values at the low end, so equal-width bins will crowd most data into the first bin."),
            QuizQuestion("pd.qcut() differs from pd.cut() because:", ["qcut uses equal-width bins", "qcut ensures equal frequency per bin", "qcut is faster", "qcut handles missing values"], 1, "qcut creates bins with approximately equal numbers of observations (quantile-based), while cut uses equal-width intervals."),
        ],
        takeaways=["Equal-width: same range per bin", "Quantile: same count per bin", "Use domain knowledge for custom bins"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_11", title="Date/Time Features", section="feature_engineering", order=11, difficulty="intermediate",
        objectives=["Extract meaningful features from datetime columns", "Capture cyclical patterns (day of week, month)", "Handle time zones and missing dates"],
        concept="Datetime columns contain hidden information: year, month, day, hour, day of week, quarter, is_weekend, days since a reference date. Cyclical features (hour, day_of_week) should be encoded with sin/cos to preserve circularity.",
        why_matters="Raw datetime strings are meaningless to models. Extracting temporal features reveals patterns like 'weekend effect', 'holiday season', or 'morning rush'.",
        example="A restaurant's sales data: December shows spikes (holidays), weekends show higher traffic, and Friday evenings peak. These patterns emerge only after extracting temporal features.",
        python_example="```python\nimport pandas as pd\nimport numpy as np\n\ndf['date'] = pd.to_datetime(df['date'])\n\ndf['year'] = df['date'].dt.year\ndf['month'] = df['date'].dt.month\ndf['day'] = df['date'].dt.day\ndf['day_of_week'] = df['date'].dt.dayofweek  # 0=Monday\ndf['is_weekend'] = (df['day_of_week'] >= 5).astype(int)\ndf['quarter'] = df['date'].dt.quarter\n\n# Cyclical encoding for day_of_week\ndf['dow_sin'] = np.sin(2 * np.pi * df['day_of_week'] / 7)\ndf['dow_cos'] = np.cos(2 * np.pi * df['day_of_week'] / 7)\n\n# Days since a reference\ndf['days_since_2020'] = (df['date'] - pd.Timestamp('2020-01-01')).dt.days\n```",
        common_mistakes=[
            "Not converting to datetime first (stays as string/object)",
            "Treating month as linear when it's cyclical (December is close to January)",
            "Including the raw datetime as a feature (too granular)",
        ],
        practice_exercise="Create temporal features from California Housing's 'housing_age' (proxy for build year). Extract 'years_since_2000' and 'decade_built'.",
        quiz=[
            QuizQuestion("Why use sin/cos encoding for day_of_week instead of raw numbers?", ["It's faster", "It preserves cyclical proximity (Sunday is close to Monday)", "It reduces dimensionality", "It handles missing values"], 1, "Day 6 (Sunday) and Day 0 (Monday) are far apart numerically but adjacent in reality. Sin/cos encoding captures this circular relationship."),
            QuizQuestion("Which datetime feature is most likely to capture weekend effects?", ["year", "month", "is_weekend", "quarter"], 2, "is_weekend (binary: 0=weekday, 1=weekend) directly captures the weekend effect."),
        ],
        takeaways=["Extract year, month, day, day_of_week, is_weekend from datetime columns", "Use sin/cos encoding for cyclical features", "Days since reference creates useful continuous features"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_12", title="Text Features", section="feature_engineering", order=12, difficulty="intermediate",
        objectives=["Extract features from text columns", "Create length-based, word-based, and pattern-based features", "Understand when text features are useful"],
        concept="Text columns contain information that simple counts can capture: string length, word count, uppercase ratio, presence of specific patterns (emails, phone numbers). For deeper analysis, TF-IDF or embeddings are used.",
        why_matters="Text columns (names, descriptions, addresses) often contain predictive signals. 'Mr' vs 'Mrs' in Titanic predicts survival. Email patterns predict spam.",
        example="Titanic Name column: 'Braund, Mr. Owen Harris' → Title='Mr'. 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)' → Title='Mrs'. Title alone explains much of the survival pattern.",
        python_example="```python\n# Basic text features\ndf['name_length'] = df['name'].str.len()\ndf['word_count'] = df['name'].str.split().str.len()\ndf['has_numbers'] = df['name'].str.contains('\\d').astype(int)\n\n# Uppercase ratio\ndf['upper_ratio'] = df['name'].apply(\n    lambda x: sum(1 for c in str(x) if c.isupper()) / max(len(str(x)), 1)\n)\n\n# Contains specific patterns\ndf['has_email'] = df['text'].str.contains(r'@', regex=True).astype(int)\n```",
        common_mistakes=[
            "Creating text features that are too specific to the training data",
            "Not handling missing values before string operations (causes errors)",
            "Using raw text directly instead of extracting structured features",
        ],
        practice_exercise="Extract text features from Titanic's Name column: title (Mr/Mrs/Miss/Other), name_length, word_count. Which is most predictive?",
        quiz=[
            QuizQuestion("Why is extracting 'Title' from Name useful in Titanic?", ["Titles are random", "Titles correlate with survival (Mr vs Mrs)", "It reduces dimensionality", "It removes the Name column"], 1, "Titles capture social status and gender — Mrs and Miss had higher survival rates than Mr."),
            QuizQuestion("Text length features are most useful for:", ["Numerical analysis", "Detecting spam, sentiment, or document classification", "Regression on house prices", "Clustering numerical data"], 1, "Text length, word count, and character patterns help distinguish document types (spam vs legitimate, positive vs negative sentiment)."),
        ],
        takeaways=["Length and word count are simple but often useful", "Pattern matching captures domain-specific signals", "For NLP tasks, use TF-IDF or embeddings instead"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_13", title="Aggregated Features", section="feature_engineering", order=13, difficulty="intermediate",
        objectives=["Create group-level aggregations", "Use merge/join to add aggregate features", "Avoid target leakage in aggregations"],
        concept="Aggregate features compute group-level statistics (mean, median, count, std) and add them back to each row. For example, average purchase amount per customer, or house price per neighbourhood.",
        why_matters="Aggregate features capture context: 'this customer's spending compared to their neighbourhood average' is more informative than raw spending.",
        example="Titanic: Average fare per passenger class. 1st class average = $84, 2nd = $21, 3rd = $13. Adding 'fare_vs_class_avg' (Fare / class_avg) captures whether a passenger paid more or less than typical for their class.",
        python_example="```python\n# Average fare per passenger class\nclass_avg = df.groupby('Pclass')['Fare'].mean().rename('avg_fare_by_class')\ndf = df.merge(class_avg, on='Pclass', how='left')\n\n# Count of passengers per ticket\nticket_counts = df.groupby('Ticket').size().rename('ticket_passengers')\ndf = df.merge(ticket_counts, on='Ticket', how='left')\n\n# WARNING: Don't aggregate on the target variable (data leakage)\n```",
        common_mistakes=[
            "Including the target variable in the aggregation (leakage)",
            "Aggregating after train/test split without handling the aggregation on test data",
            "Not handling groups with single observations (std = NaN)",
        ],
        practice_exercise="Create aggregate features on California Housing: average income per block group, average rooms per household. Do they improve predictions?",
        quiz=[
            QuizQuestion("Why is aggregating on the target variable dangerous?", ["It's computationally expensive", "It creates data leakage — the target leaks into features", "It creates missing values", "It reduces dimensionality"], 1, "If you compute mean_survived per class, you've leaked the target into a feature — the model will 'cheat' during training."),
            QuizQuestion("When computing aggregate features, you should:", ["Compute on the entire dataset", "Compute on training data only, then apply to test", "Compute after model training", "Skip aggregation entirely"], 1, "Compute aggregations on training data only to prevent leakage. Apply the same aggregation to test data."),
        ],
        takeaways=["Aggregations add group-level context", "Never aggregate on the target variable", "Fit aggregations on training data only, apply to test"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_14", title="Encoding as Feature Engineering", section="feature_engineering", order=14, difficulty="intermediate",
        objectives=["Use encoding as a feature engineering strategy", "Apply target encoding and frequency encoding", "Understand when encoding creates new information"],
        concept="Beyond basic one-hot encoding, advanced encodings create features that capture statistical relationships: target encoding (mean target per category), frequency encoding (count per category), and probability encoding.",
        why_matters="Target encoding captures the relationship between categories and the target variable, often more informative than one-hot encoding for high-cardinality features.",
        example="Titanic Embarked: 'S' has 64% survival, 'C' has 55%, 'Q' has 39%. Target encoding replaces C/S/Q with these survival rates, directly encoding the target relationship.",
        python_example="```python\n# Target encoding (mean target per category)\ntarget_means = df.groupby('city')['price'].mean()\ndf['city_encoded'] = df['city'].map(target_means)\n\n# Frequency encoding\ncounts = df['city'].value_counts()\ndf['city_freq'] = df['city'].map(counts)\n\n# Probability encoding (survival rate per category)\nsurvival_rates = df.groupby('Embarked')['Survived'].mean()\ndf['embarked_survival_rate'] = df['Embarked'].map(survival_rates)\n```",
        interpretation="Target encoding can be very powerful but risks overfitting and data leakage. Always compute encodings on training data only.",
        common_mistakes=[
            "Computing target encoding on the full dataset (leakage)",
            "Not smoothing target encodings for rare categories",
            "Using frequency encoding when category frequency is unrelated to the target",
        ],
        practice_exercise="Apply target encoding to Titanic's 'Embarked' column using training data only. Compare with one-hot encoding in a logistic regression.",
        quiz=[
            QuizQuestion("Target encoding replaces each category with:", ["A random number", "The mean of the target variable for that category", "The count of that category", "The first occurrence"], 1, "Target encoding maps each category to the average target value for observations in that category."),
            QuizQuestion("Why must target encoding be computed on training data only?", ["It's faster", "To prevent data leakage — test data target values shouldn't influence features", "pandas requires it", "It produces more accurate encodings"], 1, "Using test data target values to create features leaks information the model shouldn't have during training."),
        ],
        takeaways=["Target encoding captures category-target relationship", "Frequency encoding captures category prevalence", "Always compute encodings on training data only"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_15", title="Feature Scaling", section="feature_engineering", order=15, difficulty="intermediate",
        objectives=["Understand why scaling matters for feature engineering", "Choose the right scaler for the situation", "Apply scaling as part of a pipeline"],
        concept="Feature scaling ensures all features contribute equally to the model. Without scaling, features with larger ranges (income: 0–1M) dominate features with smaller ranges (age: 0–100). Scaling is essential for distance-based and gradient-based models.",
        why_matters="Unscaled features create biased models. KNN measures distances — income (range 1M) completely overwhelms age (range 100). StandardScaler fixes this.",
        example="California Housing: median_income ranges 0.5-15, while population ranges 3-35,000. Without scaling, population dominates distance calculations in KNN. After StandardScaler, both have mean=0, std=1.",
        python_example="```python\nfrom sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler\n\n# StandardScaler (mean=0, std=1) — default choice\nscaler = StandardScaler()\n\n# MinMaxScaler (0 to 1) — for neural networks\nscaler = MinMaxScaler()\n\n# RobustScaler (median, IQR) — for data with outliers\nscaler = RobustScaler()\n\n# Always fit on train, transform on test\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)  # no fit!\n```",
        common_mistakes=[
            "Scaling tree-based models (Random Forest, XGBoost don't need it)",
            "Fitting scaler on test data (data leakage)",
            "Not scaling before PCA (PCA is sensitive to scale)",
        ],
        practice_exercise="Apply StandardScaler to California Housing. Fit on training data, transform both train and test. Verify train mean≈0 and std≈1.",
        quiz=[
            QuizQuestion("Why must you fit the scaler on training data only?", ["It's faster", "To prevent data leakage — test data statistics shouldn't influence scaling", "pandas requires it", "Scalers can't handle test data"], 1, "Fitting on test data leaks test statistics into training, giving unrealistically good performance."),
            QuizQuestion("Which models do NOT require feature scaling?", ["KNN and SVM", "Linear Regression and Logistic Regression", "Random Forest and Gradient Boosting", "All models require scaling"], 2, "Tree-based models (Random Forest, XGBoost) split on feature thresholds, so scale doesn't affect them."),
        ],
        takeaways=["StandardScaler is the default choice", "Tree-based models don't need scaling", "Always fit on train, transform on test"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_16", title="Feature Selection", section="feature_engineering", order=16, difficulty="intermediate",
        objectives=["Distinguish feature selection from feature engineering", "Know when to create features vs remove them", "Apply both strategies in combination"],
        concept="Feature engineering creates new features. Feature selection removes existing features. Both are essential: you need good features (engineering) and only relevant ones (selection). They are complementary, not competing strategies.",
        why_matters="Too many features cause overfitting and slow training. Too few miss important patterns. The art is finding the right balance.",
        simple_explanation="Feature engineering = add information. Feature selection = remove noise. You need both.",
        example="California Housing has 8 features. After feature engineering, you might have 15. Feature selection might keep the best 6. The selected 6 engineered features outperform all 15.",
        python_example="```python\nfrom sklearn.feature_selection import SelectKBest, f_classif\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Method 1: Statistical selection\nselector = SelectKBest(f_classif, k=10)\nX_selected = selector.fit_transform(X, y)\n\n# Method 2: Model-based selection\nmodel = RandomForestClassifier(n_estimators=100)\nmodel.fit(X, y)\nimportance = pd.Series(model.feature_importances_, index=X.columns)\nimportance.nlargest(10).plot(kind='barh')\n```",
        common_mistakes=[
            "Creating hundreds of features without selecting the best ones",
            "Removing features before engineering new ones (might remove useful base features)",
            "Not measuring the impact of feature engineering or selection",
        ],
        practice_exercise="Start with California Housing's 8 features. Engineer 5 more. Use SelectKBest to select the top 8. Compare model performance.",
        quiz=[
            QuizQuestion("Feature selection and feature engineering are:", ["Opposite approaches", "Complementary strategies", "The same thing", "Only needed for large datasets"], 1, "Engineering creates useful features; selection removes useless ones. Both are necessary."),
            QuizQuestion("Why is it better to select features after engineering?", ["Selection is faster on more features", "Engineered features might be more useful than originals", "It prevents overfitting", "Both A and B"], 3, "Engineered features might outperform originals, and having more options gives selection algorithms better choices."),
        ],
        takeaways=["Engineering creates useful features, selection removes useless ones", "Both are necessary in a good pipeline", "Always measure impact on model performance"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_17", title="Correlation-Based Feature Selection", section="feature_engineering", order=17, difficulty="intermediate",
        objectives=["Remove features based on correlation", "Handle multicollinearity", "Keep the most informative feature from correlated pairs"],
        concept="Correlation-based selection removes one feature from each pair of highly correlated features (e.g., |r| > 0.9). Between two correlated features, keep the one with higher correlation to the target.",
        why_matters="Highly correlated features provide redundant information, confuse models, and increase computational cost without improving performance.",
        example="California Housing: 'total_rooms' and 'total_bedrooms' correlate at 0.93. Keeping total_rooms (higher correlation with target) and dropping total_bedrooms reduces redundancy.",
        python_example="```python\nimport numpy as np\n\n# Compute correlation matrix\ncorr_matrix = df.select_dtypes('number').corr().abs()\n\n# Find pairs with correlation > 0.9\nupper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))\nto_drop = [col for col in upper.columns if any(upper[col] > 0.9)]\n\nprint(f'Features to drop: {to_drop}')\ndf_reduced = df.drop(columns=to_drop)\n```",
        common_mistakes=[
            "Using correlation for non-linear relationships (use mutual information instead)",
            "Dropping features without checking which is more important for the target",
            "Computing correlation on categorical features without encoding first",
        ],
        practice_exercise="Compute the correlation matrix for California Housing. Drop features with |r| > 0.9. How many features remain?",
        quiz=[
            QuizQuestion("When removing correlated features, you should keep the one with:", ["Higher variance", "Higher correlation to the target", "More missing values", "Larger range"], 1, "Keep the feature more correlated with the target — it carries more predictive information."),
            QuizQuestion("A correlation threshold of 0.9 means:", ["Remove all features", "Remove one from each pair with |r| > 0.9", "Remove features with r < 0.9", "No features are removed"], 1, "Only pairs exceeding the threshold are affected — one from each pair is dropped."),
        ],
        takeaways=["Remove one from each pair of highly correlated features", "Keep the one more correlated with the target", "Use |r| > 0.9 as a threshold"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_18", title="Variance-Based Feature Selection", section="feature_engineering", order=18, difficulty="intermediate",
        objectives=["Remove near-zero variance features", "Use VarianceThreshold", "Understand when variance selection is appropriate"],
        concept="Features with near-zero variance provide almost no information because they barely change across observations. A feature where 99% of values are the same is unlikely to help any model.",
        why_matters="Constant or near-constant features waste computation and can cause numerical issues in some algorithms.",
        example="A feature 'is_valid' where 99.5% of values are 1 (True) has near-zero variance. It tells the model almost nothing — almost everyone is valid.",
        python_example="```python\nfrom sklearn.feature_selection import VarianceThreshold\n\n# Remove features with variance < 0.01\nselector = VarianceThreshold(threshold=0.01)\nX_selected = selector.fit_transform(X)\n\n# Get selected feature names\nselected_features = X.columns[selector.get_support()]\nprint(f'Removed: {set(X.columns) - set(selected_features)}')\n```",
        common_mistakes=[
            "Applying VarianceThreshold before scaling (scale affects variance)",
            "Setting threshold too high (removes useful low-variance features)",
            "Not checking what was removed",
        ],
        practice_exercise="Apply VarianceThreshold(threshold=0.01) to California Housing after scaling. Which features are removed?",
        quiz=[
            QuizQuestion("VarianceThreshold should be applied:", ["Before scaling", "After scaling", "Before splitting data", "Only on categorical features"], 1, "Scaling affects variance, so apply VarianceThreshold after scaling to get meaningful variance values."),
            QuizQuestion("A feature where 99% of values are the same has:", ["High variance", "Near-zero variance", "Medium variance", "Infinite variance"], 1, "When nearly all values are identical, the feature has very little variance and provides minimal information."),
        ],
        takeaways=["Near-zero variance features are likely useless", "Apply AFTER scaling if features have different units", "Always verify what was removed"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_19", title="Multicollinearity", section="feature_engineering", order=19, difficulty="advanced",
        objectives=["Detect multicollinearity using VIF", "Understand its effect on linear models", "Apply remedies"],
        concept="Multicollinearity occurs when two or more features are highly linearly related. It inflates coefficient standard errors in linear models, making them unreliable. Variance Inflation Factor (VIF) > 5-10 indicates problematic multicollinearity.",
        why_matters="Multicollinearity doesn't hurt tree-based models but severely damages linear regression, logistic regression, and SVM. It makes feature importance unreliable.",
        example="California Housing: 'total_rooms' and 'total_bedrooms' are highly correlated (r=0.93). In linear regression, their individual coefficients become unstable — one might be positive, the other negative, despite both being positively correlated with price.",
        python_example="```python\nfrom statsmodels.stats.outliers_influence import variance_inflation_factor\nimport pandas as pd\n\n# Compute VIF for each feature\nX_num = df.select_dtypes('number').dropna()\nvif_data = pd.DataFrame()\nvif_data['feature'] = X_num.columns\nvif_data['VIF'] = [variance_inflation_factor(X_num.values, i)\n                   for i in range(X_num.shape[1])]\nprint(vif_data.sort_values('VIF', ascending=False))\n\n# VIF > 10 → severe multicollinearity\n# VIF > 5 → moderate\n# VIF < 5 → acceptable\n```",
        common_mistakes=[
            "Ignoring multicollinearity in linear models (coefficients become meaningless)",
            "Using VIF with categorical features (encode first)",
            "Removing all correlated features when only one pair is problematic",
        ],
        practice_exercise="Compute VIF for California Housing. Which features have VIF > 10? What would you do about them?",
        quiz=[
            QuizQuestion("VIF > 10 indicates:", ["No multicollinearity", "Moderate multicollinearity", "Severe multicollinearity", "Perfect multicollinearity"], 2, "VIF > 10 means the feature's variance is inflated 10× due to correlation with other features — severe multicollinearity."),
            QuizQuestion("Multicollinearity primarily affects:", ["Tree-based models", "Linear models (regression, logistic)", "KNN", "Clustering algorithms"], 1, "Linear models estimate individual coefficients — multicollinearity makes these estimates unstable. Trees don't estimate coefficients."),
        ],
        takeaways=["VIF > 10 indicates severe multicollinearity", "Multicollinearity hurts linear models but not tree-based models", "Remedies: remove a feature, use PCA, or use regularised regression (Ridge)"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_20", title="Curse of Dimensionality", section="feature_engineering", order=20, difficulty="advanced",
        objectives=["Understand the curse of dimensionality", "Recognise when too many features hurt performance", "Apply dimensionality reduction"],
        concept="As the number of features grows, data becomes increasingly sparse. Distance metrics become meaningless (all points become equidistant), models need exponentially more data, and overfitting risk increases dramatically.",
        why_matters="In high-dimensional space, distance-based algorithms (KNN, K-Means) fail because 'nearest' loses meaning. Even with enough data, too many features cause overfitting.",
        simple_explanation="Imagine plotting 3 points in 1D — easy to see patterns. Now plot 3 points in 1000D — they're all equally far apart. That's the curse.",
        example="With 1000 features and only 100 samples, every point is equidistant from every other point. KNN can't find 'nearest' neighbours. PCA reduces 1000 features to 50 that capture 95% of variance.",
        python_example="```python\nfrom sklearn.decomposition import PCA\nfrom sklearn.feature_selection import SelectKBest, f_classif\n\n# Method 1: PCA (reduces dimensions)\npca = PCA(n_components=0.95)  # keep 95% variance\nX_pca = pca.fit_transform(X)\nprint(f'Reduced from {X.shape[1]} to {X_pca.shape[1]} features')\n\n# Method 2: SelectKBest (keeps top-k features)\nselector = SelectKBest(f_classif, k=10)\nX_selected = selector.fit_transform(X, y)\n```",
        common_mistakes=[
            "Not reducing dimensions when features >> samples",
            "Using PCA without scaling first",
            "Losing interpretability with PCA (components are combinations of all features)",
        ],
        practice_exercise="Apply PCA to California Housing. How many components are needed for 95% variance? Compare model performance with PCA vs original features.",
        quiz=[
            QuizQuestion("The curse of dimensionality means:", ["More features always improve performance", "Data becomes sparse and distances become meaningless in high dimensions", "Models train faster with more features", "Missing values increase with more features"], 1, "In high dimensions, data points become equidistant, making distance-based algorithms ineffective."),
            QuizQuestion("PCA reduces dimensions while:", ["Keeping all original features", "Preserving maximum variance", "Ensuring normal distribution", "Removing outliers"], 1, "PCA finds the directions of maximum variance and projects data onto those directions."),
        ],
        takeaways=["Too many features cause overfitting and sparse data", "PCA reduces dimensions while preserving information", "Feature selection keeps interpretable original features"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_21", title="Domain-Based Feature Engineering", section="feature_engineering", order=21, difficulty="advanced",
        objectives=["Apply domain knowledge to create features", "Work with subject matter experts", "Validate domain-engineered features"],
        concept="Domain-based feature engineering uses subject matter knowledge to create features that directly represent real-world concepts. A doctor knows which blood test combinations indicate disease. A retail analyst knows which purchase patterns signal churn.",
        why_matters="Domain features often outperform automated feature engineering because they encode causal relationships, not just correlations.",
        example="Healthcare: BMI = weight / height². Finance: debt_to_income = total_debt / annual_income. Retail: days_since_last_purchase = today - last_transaction_date. These features encode real-world knowledge.",
        python_example="```python\n# Healthcare domain\nbmi = weight_kg / (height_m ** 2)\n\n# Finance domain\ndebt_to_income = total_debt / annual_income\ncredit_utilization = credit_used / credit_limit\n\n# Retail domain\ndays_since_purchase = (pd.Timestamp.now() - df['last_purchase']).dt.days\navg_order_value = total_spent / total_orders\npurchase_frequency = total_orders / tenure_months\n```",
        common_mistakes=[
            "Creating domain features without understanding the domain",
            "Not validating with domain experts",
            "Using features that require the target to compute (leakage)",
        ],
        practice_exercise="For California Housing, create domain-based features: rooms_per_household (total_rooms/households), bedrooms_ratio (total_bedrooms/total_rooms). Do they improve predictions?",
        quiz=[
            QuizQuestion("Domain-based features are powerful because they:", ["Are always numerical", "Encode real-world causal relationships", "Require no preprocessing", "Work with any algorithm"], 1, "Domain features encode understanding of how the real world works, not just statistical correlations."),
            QuizQuestion("Before deploying domain-based features, you should:", ["Use them immediately", "Validate with domain experts and test performance impact", "Apply them to all datasets", "Remove them if they're too complex"], 1, "Always validate that domain features actually improve performance and make sense to subject matter experts."),
        ],
        takeaways=["Domain knowledge creates the most powerful features", "Work with subject matter experts", "Always validate with domain experts"],
        lab_module="feature_engineering",
    ),
    Topic(
        id="fe_22", title="Feature Engineering Case Study", section="feature_engineering", order=22, difficulty="advanced",
        objectives=["Apply all techniques to a real dataset", "Document feature engineering decisions", "Measure impact on model performance"],
        concept="A feature engineering case study walks through the complete process: understand the problem → explore data → brainstorm features → implement → test → iterate. The Titanic dataset is a classic example.",
        why_matters="Feature engineering is iterative. The first attempt is rarely the best. This case study shows the systematic approach.",
        example="Titanic feature engineering:\n1. Title from Name → Mr/Mrs/Miss/Master\n2. FamilySize from SibSp + Parch + 1\n3. IsAlone from FamilySize == 1\n4. Fare per person from Fare / FamilySize\n5. Age groups from pd.cut()\n6. Cabin deck from Cabin[0]\nResult: Model accuracy improves from ~78% to ~83%.",
        python_example="```python\nimport pandas as pd\nimport numpy as np\n\ndf = pd.read_csv('titanic.csv')\n\n# 1. Title extraction\ndf['Title'] = df['Name'].str.extract(r' ([A-Za-z]+)\\.')\ndf['Title'] = df['Title'].replace(['Lady','Countess','Capt','Col','Don',\n    'Dr','Major','Rev','Sir','Jonkheer','Dona'], 'Rare')\ndf['Title'] = df['Title'].replace('Mlle', 'Miss')\ndf['Title'] = df['Title'].replace('Ms', 'Miss')\ndf['Title'] = df['Title'].replace('Mme', 'Mrs')\n\n# 2. Family features\ndf['FamilySize'] = df['SibSp'] + df['Parch'] + 1\ndf['IsAlone'] = (df['FamilySize'] == 1).astype(int)\n\n# 3. Fare per person\ndf['FarePerPerson'] = df['Fare'] / df['FamilySize']\n\n# 4. Age groups\ndf['AgeGroup'] = pd.cut(df['Age'], bins=[0,12,18,35,60,100],\n    labels=['Child','Teen','Young','Middle','Senior'])\n\n# 5. Cabin deck\ndf['Deck'] = df['Cabin'].str[0].fillna('Unknown')\n```",
        common_mistakes=[
            "Creating too many features without measuring impact",
            "Not handling NaN values before feature engineering",
            "Forgetting to apply the same transformations to test data",
        ],
        practice_exercise="Perform the complete Titanic feature engineering case study. Train a Random Forest before and after. Report the accuracy improvement.",
        quiz=[
            QuizQuestion("In the Titanic case study, Title is extracted from Name because:", ["Names are unstructured text", "Titles encode social status and gender that correlate with survival", "It reduces the number of columns", "It removes missing values"], 1, "Titles like 'Mrs' and 'Miss' indicate gender and social status, both of which strongly correlate with survival probability."),
            QuizQuestion("The most important principle in feature engineering is:", ["Create as many features as possible", "Measure the impact of each feature on model performance", "Only use automated feature engineering", "Focus on algorithm tuning instead"], 1, "Always measure whether your engineered features actually improve performance — don't create features blindly."),
        ],
        takeaways=["Feature engineering is iterative: create → test → keep or discard", "Small, meaningful features often outperform many auto-generated ones", "Always document what you created and why"],
        lab_module="feature_engineering",
    ),
]
