"""Preprocessing curriculum — 20 topics with full educational content."""

from learning import QuizQuestion, Topic

TOPICS = [
    Topic(id="pp_01", title="Why Preprocessing is Required", section="preprocessing", order=1, difficulty="beginner",
        objectives=["Understand why preprocessing is essential", "Recognise raw data problems", "See the impact on model performance"],
        concept="Before any model can work, data must be clean, complete, and in the right format. Preprocessing transforms raw data into model-ready data.",
        why_matters="Models cannot handle missing values, text categories, or unscaled features. Preprocessing is the bridge between raw data and modelling.",
        simple_explanation="Raw data is messy. Preprocessing cleans it so models can understand it.",
        example="Raw Titanic data has: missing ages (19.8% NaN), cabin numbers (77% NaN), text 'male/female', text port names. A model cannot process 'male' or NaN — preprocessing converts these to numbers.",
        common_mistakes=["Skipping preprocessing and hoping the model handles it", "Not documenting preprocessing steps"],
        practice_exercise="Load a dataset and count: how many columns have missing values? How many have text/categorical data? These are the columns that need preprocessing.",
        quiz=[QuizQuestion(question="Why can't you skip preprocessing?", options=["Models handle raw data automatically", "Missing values and text categories crash or mislead models", "Preprocessing is optional for tree models", "It only matters for deep learning"], correct_index=1, explanation="Models like Logistic Regression and KNN cannot process missing values or text. Even tree models work better with proper preprocessing.")],
        takeaways=["Preprocessing is mandatory before modelling", "Every step must be reproducible", "Document all transformations"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_02", title="MCAR/MAR/MNAR Missing Data", section="preprocessing", order=2, difficulty="intermediate",
        objectives=["Distinguish MCAR, MAR, MNAR", "Choose appropriate imputation strategy", "Understand missingness mechanisms"],
        concept="MCAR: missing completely at random (no pattern — the missingness is unrelated to any variable). MAR: missing depends on observed data (e.g., men skip the 'depressed' question more). MNAR: missing depends on the value itself (e.g., high-income people don't report income).",
        why_matters="The missingness mechanism determines which imputation method is appropriate. Using mean imputation on MNAR data biases results significantly.",
        simple_explanation="Is the missingness random (MCAR), predictable from other columns (MAR), or related to the value itself (MNAR)?",
        example="Survey data: income is MNAR (rich people hide income). Age is MCAR (random data entry errors). Blood pressure is MAR (sicker patients miss appointments more).",
        common_mistakes=["Assuming all missing data is random", "Not testing for missingness patterns", "Using mean imputation when data is MNAR"],
        practice_exercise="Examine missing patterns in a dataset. For each column with missing values, hypothesize whether it's MCAR, MAR, or MNAR. Check if missingness correlates with other columns.",
        quiz=[QuizQuestion(question="Income data is missing more often for high earners. This is:", options=["MCAR — completely random", "MAR — depends on observed data", "MNAR — missingness depends on the value itself", "Impossible to determine"], correct_index=2, explanation="When high earners hide their income, the missingness depends on the value itself — that's MNAR. This cannot be fixed by simple imputation.")],
        takeaways=["MCAR → mean/median imputation is safe", "MAR → include related features in imputation", "MNAR → harder to handle, consider domain knowledge"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_03", title="Removing Missing Values", section="preprocessing", order=3, difficulty="beginner",
        objectives=["Use df.dropna() correctly", "Know when dropping is appropriate", "Assess information loss"],
        concept="df.dropna() removes rows with missing values. Acceptable when <5% missing and data is MCAR. Otherwise, you lose information that may be valuable.",
        why_matters="Dropping is the simplest approach but loses data. With 30% missing, dropping loses 30% of your information — potentially eliminating important patterns.",
        simple_explanation="If a few rows have holes, you can remove them. If many rows have holes, you need to fill them instead.",
        python_example="```python\ndf.dropna()                    # drop any row with NaN\ndf.dropna(subset=['age'])       # only check 'age'\ndf.dropna(thresh=10)            # keep rows with ≥10 non-NaN values\n\n# Check what you're losing\ndropped = df[df.isnull().any(axis=1)]\nprint(f'Dropping {len(dropped)} rows ({len(dropped)/len(df)*100:.1f}%)')\n```",
        common_mistakes=["Dropping >20% of rows without checking impact", "Not investigating what you're losing", "Dropping before checking if other columns are affected"],
        practice_exercise="Drop rows with missing values. 1. How many rows remain? 2. Did you lose any class representation? 3. Would imputation be better?",
        quiz=[QuizQuestion(question="When is dropping missing values acceptable?", options=["Always — it's the safest approach", "When <5% of rows are missing and the data is MCAR", "When any columns have missing values", "Only for categorical data"], correct_index=1, explanation="Dropping is only safe when very few rows are affected (<5%) and the missingness is random (MCAR). Otherwise, you lose valuable data or introduce bias.")],
        takeaways=["Drop only when <5% missing", "Check which rows are lost", "Consider imputation for larger amounts"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_04", title="Mean Imputation", section="preprocessing", order=4, difficulty="beginner",
        objectives=["Apply mean imputation", "Understand its limitations", "Know when mean is appropriate"],
        concept="Fill missing values with the column mean. Simple but reduces variance and distorts distributions. Only appropriate for MCAR data that is roughly symmetric.",
        why_matters="Mean imputation is quick but statistically problematic — it underestimates variance and biases correlations toward zero.",
        simple_explanation="Replace blanks with the average. Quick fix, but not always the best fix.",
        python_example="```python\ndf['age'] = df['age'].fillna(df['age'].mean())\n# Or with sklearn:\nfrom sklearn.impute import SimpleImputer\nimputer = SimpleImputer(strategy='mean')\ndf[num_cols] = imputer.fit_transform(df[num_cols])\n```",
        common_mistakes=["Using mean when data is skewed (use median instead)", "Fitting imputer on all data before splitting (data leakage)", "Not checking if variance decreases after imputation"],
        practice_exercise="Compare the age distribution before and after mean imputation. 1. Did the variance decrease? 2. Is the distribution more peaked? 3. Would median be better?",
        quiz=[QuizQuestion(question="Mean imputation is problematic because:", options=["It's too slow", "It reduces variance and biases correlations", "It doesn't work with sklearn", "It only works for categorical data"], correct_index=1, explanation="Mean imputation shrinks variance because imputed values are all the same (the mean). This biases correlations toward zero and makes the data look less variable than it really is.")],
        takeaways=["Mean imputation is simple but reduces variance", "Only for MCAR data with symmetric distribution", "Use median for skewed distributions"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_05", title="Median Imputation", section="preprocessing", order=5, difficulty="beginner",
        objectives=["Apply median imputation", "Know when median beats mean", "Compare imputation strategies"],
        concept="Fill with the median — the middle value. Robust to outliers and skewed distributions. Preferred over mean for most real-world data.",
        why_matters="Median is not pulled by extreme values, making it a safer default for imputation. House prices: mean=£350K (inflated by mansions), median=£220K (more typical).",
        simple_explanation="The median is the 'typical' value. Outliers don't affect it.",
        python_example="```python\ndf['income'] = df['income'].fillna(df['income'].median())\n# Or with sklearn:\nimputer = SimpleImputer(strategy='median')\n```",
        common_mistakes=["Using median for perfectly symmetric data where mean is equivalent", "Forgetting to check distribution first", "Not comparing mean vs median before choosing"],
        practice_exercise="For a skewed column: 1. Calculate mean and median. 2. How different are they? 3. Which is more representative of a 'typical' value?",
        quiz=[QuizQuestion(question="When is median imputation preferred over mean?", options=["When data is perfectly symmetric", "When data has outliers or is skewed", "When there are no missing values", "For categorical data"], correct_index=1, explanation="Median is robust to outliers — extreme values don't affect it. For skewed data (e.g., income), the median better represents a 'typical' value.")],
        takeaways=["Median is robust to outliers", "Preferred default for skewed data", "Use when distribution is not normal"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_06", title="Mode Imputation", section="preprocessing", order=6, difficulty="beginner",
        objectives=["Apply mode imputation for categorical data", "Understand when mode is appropriate", "Check if mode is dominant"],
        concept="Fill with the most frequent value. Used for categorical columns where mean/median don't apply (you can't average 'Red' and 'Blue').",
        why_matters="Categorical columns cannot use mean/median. Mode is the standard imputation for text/categorical features.",
        simple_explanation="Fill blanks with the most common value.",
        python_example="```python\ndf['city'] = df['city'].fillna(df['city'].mode()[0])\n# Or with sklearn:\nimputer = SimpleImputer(strategy='most_frequent')\n```",
        common_mistakes=["Using mode for numerical data (use mean/median instead)", "Not checking if mode represents >50% of data (bias)", "Using mode when 'Unknown' would be more honest"],
        practice_exercise="Find the mode of a categorical column. 1. What is the mode? 2. What percentage of data does it represent? 3. Would 'Unknown' be a better imputation?",
        quiz=[QuizQuestion(question="Why use mode instead of mean for categorical data?", options=["Mode is faster", "Mean cannot be computed for text categories", "Mode always gives better results", "sklearn requires it"], correct_index=1, explanation="You cannot compute the mean of 'Red', 'Blue', and 'Green'. Mode (most frequent value) is the only meaningful central tendency measure for nominal categories.")],
        takeaways=["Mode = most frequent value", "Use for categorical features", "Check if mode is dominant (>50%)"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_07", title="Constant Imputation", section="preprocessing", order=7, difficulty="intermediate",
        objectives=["Apply constant imputation", "Understand when missingness carries information", "Add indicator columns"],
        concept="Fill with a fixed value (0, -1, 'Unknown'). Useful when missingness itself carries information — the fact that a value is missing is meaningful.",
        why_matters="Sometimes 'missing' means 'not applicable' (e.g., no garage → 0 garage cars). Constant imputation preserves this signal. Adding an 'is_missing' indicator column makes this explicit.",
        simple_explanation="Replace blanks with a specific value. The value 'Unknown' or -1 signals that data was absent.",
        python_example="```python\ndf['garage'] = df['garage'].fillna(0)\n# Or:\nimputer = SimpleImputer(strategy='constant', fill_value='Unknown')\n\n# Add indicator column\ndf['garage_missing'] = df['garage'].isnull().astype(int)\ndf['garage'] = df['garage'].fillna(0)\n```",
        common_mistakes=["Using 0 when it has numerical meaning (0 income is different from missing income)", "Not creating a separate 'is_missing' indicator column", "Not explaining to the model why the value was missing"],
        practice_exercise="For a column with 30% missing values: 1. Create an 'is_missing' indicator. 2. Does the missingness correlate with the target? 3. If yes, the indicator is a useful feature.",
        quiz=[QuizQuestion(question="Why add an 'is_missing' indicator column?", options=["It speeds up training", "Missingness itself may be a useful predictive feature", "It's required by sklearn", "It prevents data leakage"], correct_index=1, explanation="If data is missing for a reason (e.g., sicker patients skip questions), the missingness pattern itself predicts the outcome. The indicator makes this explicit.")],
        takeaways=["Constant imputation preserves missingness signal", "Consider adding an 'is_missing' indicator", "Use domain knowledge to choose the value"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_08", title="Duplicate Data", section="preprocessing", order=8, difficulty="beginner",
        objectives=["Detect and remove duplicates", "Understand when duplicates are legitimate", "Prevent data leakage from duplicates"],
        concept="Duplicate rows are exact copies. They bias model training — the model sees the same examples twice, inflating the importance of those patterns.",
        why_matters="Duplicates inflate statistics and can cause data leakage if both copies end up in train and test sets (one copy in each).",
        simple_explanation="Duplicate = same data entered twice. Remove to get clean, accurate data.",
        python_example="```python\ndf.duplicated().sum()           # count duplicates\ndf.drop_duplicates()           # remove\ndf.drop_duplicates(subset=['id'])  # by specific columns\n\n# Check before removing\nprint(f'Found {df.duplicated().sum()} duplicate rows')\n```",
        common_mistakes=["Removing legitimate duplicates (e.g., same person, different time points)", "Not resetting index after dropping", "Not checking if duplicates span train/test split"],
        practice_exercise="1. Count duplicates in a dataset. 2. Examine a few duplicate rows — are they truly identical? 3. Remove them and re-count.",
        quiz=[QuizQuestion(question="Why are duplicate rows dangerous in ML?", options=["They crash the model", "They cause data leakage if one copy is in train and another in test", "They slow down training", "They only matter for small datasets"], correct_index=1, explanation="If duplicate rows end up in both train and test sets, the model has 'seen' those test examples during training. This inflates test scores and produces misleading evaluation.")],
        takeaways=["Always check for duplicates", "Investigate before removing (some are legitimate)", "Duplicates bias model training and can cause data leakage"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_09", title="Outlier Detection (IQR)", section="preprocessing", order=9, difficulty="intermediate",
        objectives=["Detect outliers using IQR method", "Decide how to handle outliers", "Distinguish errors from genuine extremes"],
        concept="IQR method: outliers are values below Q1 - 1.5*IQR or above Q3 + 1.5*IQR. IQR = Q3 - Q1 (the middle 50%). Handle by removing, capping (winsorising), or transforming.",
        why_matters="Outliers distort means, correlations, and model training. Some models (linear regression, KNN) are very sensitive to them. But not all outliers are errors.",
        simple_explanation="Outliers are unusually extreme values. They may be data entry errors or genuine extremes that need investigation.",
        python_example="```python\nQ1, Q3 = df['fare'].quantile([0.25, 0.75])\nIQR = Q3 - Q1\nlower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR\n\noutliers = df[(df['fare'] < lower) | (df['fare'] > upper)]\nprint(f'Found {len(outliers)} outliers ({len(outliers)/len(df)*100:.1f}%)')\n\n# Cap instead of remove\ndf['fare'] = df['fare'].clip(lower, upper)\n```",
        common_mistakes=["Removing all outliers without investigation", "Not distinguishing errors from genuine extremes", "Removing outliers from test data (only handle in training)"],
        practice_exercise="Apply IQR outlier detection to a numerical column. 1. How many outliers? 2. Examine them — are they errors or real? 3. Try capping vs removing. Which preserves more data?",
        quiz=[QuizQuestion(question="A fare value of £500 is detected as an outlier. Before removing it, you should:", options=["Remove it immediately — it's an outlier", "Investigate whether it's a data entry error or a genuine first-class ticket", "Convert it to the median", "Ignore the IQR method"], correct_index=1, explanation="Outliers aren't always errors. A £500 fare might be a genuine first-class transatlantic ticket. Removing genuine data loses information and biases the model.")],
        takeaways=["IQR: beyond Q1-1.5*IQR or Q3+1.5*IQR", "Always investigate before removing", "Consider capping instead of removing"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_10", title="Standardization (Z-score)", section="preprocessing", order=10, difficulty="intermediate",
        objectives=["Apply StandardScaler", "Know when to standardise", "Understand the formula"],
        concept="StandardScaler: (x - mean) / std → mean=0, std=1. Essential for distance-based algorithms: KNN, SVM, Logistic Regression, K-Means. Without it, features with larger ranges dominate.",
        why_matters="Income ($50K) overwhelms Age (30) in Euclidean distance. Standardisation puts all features on the same scale so each contributes equally.",
        simple_explanation="Scaling puts all features on the same scale (mean 0, standard deviation 1) so no single feature dominates.",
        python_example="```python\nfrom sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)  # fit + transform\nX_test_scaled = scaler.transform(X_test)        # transform only!\n```",
        common_mistakes=["Fitting scaler on test data (data leakage!)", "Scaling tree-based models (they don't need it)", "Scaling before handling missing values (NaN propagates)"],
        practice_exercise="1. Scale features with StandardScaler. 2. Check mean ≈ 0 and std ≈ 1. 3. Train KNN with and without scaling. How much does accuracy improve?",
        quiz=[QuizQuestion(question="Why must you fit StandardScaler on training data only?", options=["It's faster", "Fitting on test data leaks test information into training", "sklearn requires it", "It doesn't matter"], correct_index=1, explanation="If you fit the scaler on the full dataset, the scaler sees the test data's mean and std. This leaks information — the model indirectly 'knows' the test data distribution.")],
        takeaways=["StandardScaler: mean=0, std=1", "Always fit on train, transform on test (never fit on test)", "Essential for KNN, SVM, K-Means, Logistic Regression"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_11", title="Min-Max Scaling", section="preprocessing", order=11, difficulty="intermediate",
        objectives=["Apply MinMaxScaler", "Compare with StandardScaler", "Know when MinMax is appropriate"],
        concept="MinMaxScaler scales features to [0, 1]: (x - min) / (max - min). Sensitive to outliers — one extreme value squashes everything else into a tiny range.",
        why_matters="MinMax is useful when you need bounded values (e.g., neural networks, image pixel values). But StandardScaler is usually preferred for tabular data.",
        simple_explanation="Squishes everything into the range 0 to 1.",
        python_example="```python\nfrom sklearn.preprocessing import MinMaxScaler\nscaler = MinMaxScaler()\nX_scaled = scaler.fit_transform(X_train)\n```",
        common_mistakes=["Using MinMax when outliers are present (one outlier squashes everything)", "Confusing with StandardScaler", "Not fitting on train only"],
        practice_exercise="Apply MinMax scaling to a column with an outlier. 1. What happens to most values? 2. Compare with StandardScaler. Which handles the outlier better?",
        quiz=[QuizQuestion(question="Why is MinMaxScaler sensitive to outliers?", options=["It's slower", "An extreme value changes the min or max, squashing all other values into a tiny range", "It doesn't work with NaN", "It requires integer input"], correct_index=1, explanation="MinMax uses the actual min and max. If one value is 1000x larger than typical values, everything else is compressed into a tiny fraction of the [0,1] range.")],
        takeaways=["MinMax: [0, 1] range", "Sensitive to outliers", "StandardScaler is usually preferred for tabular data"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_12", title="Robust Scaling", section="preprocessing", order=12, difficulty="intermediate",
        objectives=["Apply RobustScaler", "Know when outliers demand robust scaling", "Compare with StandardScaler"],
        concept="RobustScaler uses median and IQR instead of mean and std. Resistant to outliers. Formula: (x - median) / IQR. Best when data has extreme values that are genuine.",
        why_matters="When outliers are genuine (not errors), RobustScaler preserves the central distribution while handling extremes gracefully.",
        simple_explanation="Scaling that doesn't care about outliers — uses the median instead of the mean.",
        python_example="```python\nfrom sklearn.preprocessing import RobustScaler\nscaler = RobustScaler()  # uses median, IQR\nX_scaled = scaler.fit_transform(X_train)\n```",
        common_mistakes=["Using RobustScaler when data is already clean (StandardScaler is fine)", "Forgetting to still handle missing values first", "Not comparing the results with StandardScaler"],
        practice_exercise="Compare StandardScaler and RobustScaler on a dataset with outliers. 1. How do the scaled distributions differ? 2. Which preserves more of the original distribution shape?",
        quiz=[QuizQuestion(question="RobustScaler uses which statistics instead of mean and std?", options=["Min and Max", "Median and IQR", "Mode and Range", "Mean and variance"], correct_index=1, explanation="RobustScaler uses the median (robust central tendency) and IQR (robust spread), both of which are unaffected by outliers. This makes it robust to extreme values.")],
        takeaways=["RobustScaler: uses median and IQR", "Best when data has genuine outliers", "Resistant to extreme values"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_13", title="Label Encoding", section="preprocessing", order=13, difficulty="beginner",
        objectives=["Apply label encoding", "Know when it's appropriate", "Avoid misusing on nominal data"],
        concept="Label encoding assigns integers: low=0, medium=1, high=2. Only for ordinal data (has natural order). Misuse on nominal data implies false ordering that the model may exploit incorrectly.",
        why_matters="Label encoding on nominal data (e.g., Red=0, Blue=1, Green=2) tells the model that Red < Blue, which is meaningless and can bias results.",
        simple_explanation="Label encoding = assign numbers to categories. Only works when the numbers make sense (ordered categories).",
        python_example="```python\nfrom sklearn.preprocessing import LabelEncoder\nle = LabelEncoder()\ndf['size_encoded'] = le.fit_transform(df['size'])\n# low=0, medium=1, high=2\n```",
        common_mistakes=["Using label encoding for nominal data (use one-hot instead)", "Forgetting the mapping is arbitrary (0,1,2 not necessarily in that order)", "Not saving the encoder for inverse transform"],
        practice_exercise="Encode 'size' (low/medium/high) with LabelEncoder. 1. What integers were assigned? 2. Does the ordering make sense? 3. Now try encoding 'color' (red/blue/green) — is this correct?",
        quiz=[QuizQuestion(question="When is label encoding appropriate?", options=["For any categorical data", "Only for ordinal categories with a natural order", "Only for binary variables", "Never"], correct_index=1, explanation="Label encoding assigns integers that imply ordering. This is correct only for ordinal data (low < medium < high) but misleading for nominal data (Red is not less than Blue).")],
        takeaways=["Label encoding: integers for ordered categories only", "Don't use for nominal (unordered) data", "For nominal → use one-hot encoding"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_14", title="One-Hot Encoding", section="preprocessing", order=14, difficulty="beginner",
        objectives=["Apply one-hot encoding", "Avoid high-cardinality problems", "Understand dummy variable trap"],
        concept="Creates binary columns: color_red, color_blue, color_green (0 or 1). For nominal data (no natural order). Avoid for high-cardinality features (500 cities = 500 new columns).",
        why_matters="One-hot encoding is the standard for nominal categories. But creating too many columns increases dimensionality and can cause multicollinearity.",
        simple_explanation="One-hot = create a yes/no column for each category. No false ordering.",
        python_example="```python\ndf = pd.get_dummies(df, columns=['color'])\n# Or with sklearn:\nfrom sklearn.preprocessing import OneHotEncoder\nencoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)\n```",
        common_mistakes=["One-hot encoding the target variable", "Creating too many columns (high cardinality)", "Fitting encoder on test data (data leakage)", "Not using handle_unknown='ignore'"],
        practice_exercise="One-hot encode a categorical column. 1. How many new columns were created? 2. What happens to a new category not seen during training? 3. Try with handle_unknown='ignore'.",
        quiz=[QuizQuestion(question="What problem occurs with one-hot encoding a column with 500 unique values?", options=["It's fine — more features is better", "Creates 500 new columns, increasing dimensionality and risking overfitting", "sklearn crashes", "The model becomes faster"], correct_index=1, explanation="500 new columns dramatically increases dimensionality. With few samples, this causes overfitting. For high-cardinality features, consider target encoding or feature hashing.")],
        takeaways=["One-hot: binary columns for nominal data", "Avoid for >50 unique categories", "Always use handle_unknown='ignore'"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_15", title="Ordinal Encoding", section="preprocessing", order=15, difficulty="intermediate",
        objectives=["Apply ordinal encoding correctly", "Define category order explicitly", "Compare with label encoding"],
        concept="Maps categories to ordered integers based on a defined ranking: {'low':0, 'medium':1, 'high':2}. Like LabelEncoder but you specify the order explicitly, which is safer.",
        why_matters="Ordinal encoding preserves the rank information that one-hot encoding loses. Essential for features like education level (high school < bachelor < master < PhD).",
        simple_explanation="Like label encoding, but you define the order explicitly to avoid mistakes.",
        python_example="```python\nfrom sklearn.preprocessing import OrdinalEncoder\noe = OrdinalEncoder(categories=[['low', 'medium', 'high']])\ndf['size'] = oe.fit_transform(df[['size']])\n```",
        common_mistakes=["Using ordinal encoding for nominal data", "Forgetting to define the correct order", "Assuming sklearn guesses the order"],
        practice_exercise="Encode education level (high_school, bachelor, master, PhD) with OrdinalEncoder. 1. Define the correct order. 2. What integers are assigned? 3. Compare with one-hot encoding.",
        quiz=[QuizQuestion(question="How does OrdinalEncoder differ from LabelEncoder?", options=["They are identical", "OrdinalEncoder lets you specify the category order; LabelEncoder assigns arbitrary integers", "OrdinalEncoder is faster", "OrdinalEncoder works only on text"], correct_index=1, explanation="OrdinalEncoder requires you to specify the order (e.g., [['low','medium','high']]), ensuring the integers reflect the true ranking. LabelEncoder assigns integers alphabetically or by appearance.")],
        takeaways=["Ordinal encoding: ordered categories with explicit order", "You must define the order", "Use when categories have a natural ranking"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_16", title="Train/Test Split", section="preprocessing", order=16, difficulty="beginner",
        objectives=["Split data correctly", "Use stratification for classification", "Understand why splitting matters"],
        concept="Split data into training (to learn) and testing (to evaluate). Standard: 80/20 or 70/30. Use stratify=y for imbalanced classes to maintain class proportions in both sets.",
        why_matters="Evaluating on training data measures memorisation, not generalisation. The test set simulates unseen future data — the only honest measure of performance.",
        simple_explanation="Train = homework (model learns). Test = exam (model proves it learned).",
        python_example="```python\nfrom sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42, stratify=y\n)\nprint(f'Train: {len(X_train)}, Test: {len(X_test)}')\n```",
        common_mistakes=["Not using stratify for imbalanced data", "Fitting preprocessing before splitting (data leakage)", "Not setting random_state (non-reproducible)"],
        practice_exercise="Split a dataset with 80/20 ratio. 1. Check class proportions in train and test. 2. Do they match? 3. Now split without stratify — what happens?",
        quiz=[QuizQuestion(question="Why use stratify=y when splitting?", options=["It's faster", "It ensures train and test sets have the same class proportions", "It prevents data leakage", "It's required by sklearn"], correct_index=1, explanation="Stratification ensures the class distribution in train and test matches the original data. Without it, a rare class might end up entirely in test, making evaluation unreliable.")],
        takeaways=["Always split before preprocessing", "Use stratify for classification", "Set random_state for reproducibility"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_17", title="Data Leakage", section="preprocessing", order=17, difficulty="intermediate",
        objectives=["Identify data leakage", "Prevent leakage in pipelines", "Understand consequences"],
        concept="Data leakage occurs when test information leaks into training. Causes: fitting preprocessing on all data, using future data in time-series, or target leakage (features derived from the target).",
        why_matters="Leaked models look great in testing but fail in production. It's the most dangerous mistake in ML — you think your model works, but it's cheating.",
        simple_explanation="Data leakage = your model accidentally saw the test answers during training.",
        python_example="```python\n# WRONG: data leakage\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)  # fit on ALL data!\nX_train, X_test, ... = train_test_split(X_scaled, ...)\n\n# CORRECT: no leakage\nX_train, X_test, ... = train_test_split(X, ...)\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)\n```",
        common_mistakes=["Fitting scaler/imputer on entire dataset before splitting", "Using features derived from the target", "Not using Pipeline (manual fit/transform is error-prone)"],
        practice_exercise="1. Split data first, then fit scaler on training data only. 2. Transform test data with the training scaler. 3. Compare the test scaler's mean/std with the training scaler's.",
        quiz=[QuizQuestion(question="Which is a form of data leakage?", options=["Scaling features", "Fitting preprocessing on the full dataset before train/test split", "Using cross-validation", "Setting random_state"], correct_index=1, explanation="Fitting preprocessing on the full dataset lets the scaler/imputer see test data statistics. This information leaks into training, producing overly optimistic test scores.")],
        takeaways=["Always fit preprocessing on train only", "Use sklearn Pipeline to prevent leakage", "Never use test data statistics during training"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_18", title="Sklearn Pipelines", section="preprocessing", order=18, difficulty="intermediate",
        objectives=["Build Pipelines", "Understand how Pipelines prevent leakage", "Use Pipeline with cross-validation"],
        concept="Pipeline chains preprocessing and model into one object. When used with cross-validation, preprocessing is fitted only on training folds — automatically preventing leakage.",
        why_matters="Pipelines are the gold standard for preventing data leakage and ensuring reproducibility. They make your workflow atomic and portable.",
        simple_explanation="A Pipeline = a chain of steps. It handles preprocessing and modelling in one object, preventing data leakage automatically.",
        python_example="```python\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n\npipeline = Pipeline([\n    ('scaler', StandardScaler()),\n    ('model', LogisticRegression())\n])\npipeline.fit(X_train, y_train)\nscore = pipeline.score(X_test, y_test)\n```",
        common_mistakes=["Not using Pipeline (manual fit/transform is error-prone and leaky)", "Forgetting to pass the full pipeline to cross_val_score", "Not using Pipeline for hyperparameter tuning"],
        practice_exercise="Build a Pipeline with StandardScaler and Random Forest. 1. Fit on training data. 2. Score on test data. 3. Use with cross_val_score — does the score change?",
        quiz=[QuizQuestion(question="Why do Pipelines prevent data leakage during cross-validation?", options=["They don't — pipelines are just convenience", "Each fold's preprocessing is fitted only on that fold's training data", "Pipelines always use the test set", "Pipelines skip preprocessing"], correct_index=1, explanation="When a Pipeline is used with cross_val_score, each CV fold fits the preprocessing steps on that fold's training data only. The test fold is never seen during fitting — preventing leakage.")],
        takeaways=["Pipeline prevents data leakage", "One object for fit/predict", "Always use with cross-validation"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_19", title="ColumnTransformer", section="preprocessing", order=19, difficulty="intermediate",
        objectives=["Apply different preprocessing to different columns", "Build complete preprocessing pipelines", "Handle mixed data types"],
        concept="ColumnTransformer applies different preprocessing to different column groups: StandardScaler for numerical, OneHotEncoder for categorical. Essential for real datasets with mixed types.",
        why_matters="Real datasets have mixed types. You can't scale categories or encode numbers. ColumnTransformer handles both in one object.",
        simple_explanation="Apply the right transformation to the right columns automatically.",
        python_example="```python\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\n\npreprocessor = ColumnTransformer([\n    ('num', Pipeline([('scaler', StandardScaler())]), num_cols),\n    ('cat', Pipeline([('encoder', OneHotEncoder(handle_unknown='ignore'))]), cat_cols)\n])\n\nfull_pipeline = Pipeline([\n    ('preprocessor', preprocessor),\n    ('model', RandomForestClassifier())\n])\n```",
        common_mistakes=["Applying the same preprocessing to all columns", "Forgetting remainder='passthrough' for unlisted columns", "Not using Pipeline inside ColumnTransformer"],
        practice_exercise="Build a ColumnTransformer: StandardScaler for numerical, OneHotEncoder for categorical. 1. How many columns does the output have? 2. What happens to unlisted columns?",
        quiz=[QuizQuestion(question="What does ColumnTransformer do?", options=["Transforms all columns the same way", "Applies different preprocessing to different column groups", "Reduces the number of columns", "Only works with numerical data"], correct_index=1, explanation="ColumnTransformer lets you specify different preprocessing for different column groups — scaling for numerical, encoding for categorical — in one object.")],
        takeaways=["ColumnTransformer: different preprocessing per column group", "Numerical → scale, Categorical → encode", "Combine with Pipeline for complete workflow"],
        lab_module="preprocessing",
    ),
    Topic(id="pp_20", title="Preprocessing Best Practices", section="preprocessing", order=20, difficulty="advanced",
        objectives=["Follow preprocessing best practices", "Create reproducible workflows", "Review the complete preprocessing checklist"],
        concept="Best practices checklist:\n1. Split data first (before any preprocessing)\n2. Fit preprocessing on training data only\n3. Use Pipeline and ColumnTransformer\n4. Check distributions before and after\n5. Document every step\n6. Handle missing values before scaling\n7. Scale numerical, encode categorical separately\n8. Save fitted preprocessors for production",
        why_matters="Following best practices prevents the most common and dangerous mistakes in machine learning: data leakage, non-reproducible results, and biased evaluation.",
        simple_explanation="The rules that prevent data leakage and ensure reproducible, trustworthy results.",
        python_example="```python\n# Complete best-practice workflow\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder\nfrom sklearn.model_selection import train_test_split\n\n# 1. Split first\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# 2. Build preprocessing pipeline\npreprocessor = ColumnTransformer([\n    ('num', Pipeline([\n        ('imputer', SimpleImputer(strategy='median')),\n        ('scaler', StandardScaler())\n    ]), num_cols),\n    ('cat', Pipeline([\n        ('imputer', SimpleImputer(strategy='most_frequent')),\n        ('encoder', OneHotEncoder(handle_unknown='ignore'))\n    ]), cat_cols)\n])\n\n# 3. Full pipeline\npipeline = Pipeline([\n    ('preprocessor', preprocessor),\n    ('model', RandomForestClassifier(random_state=42))\n])\n\n# 4. Train and evaluate — all within the pipeline\npipeline.fit(X_train, y_train)\nprint(f'Score: {pipeline.score(X_test, y_test):.3f}')\n```",
        common_mistakes=["Not documenting preprocessing steps", "Doing steps in wrong order", "Not checking results after each step", "Not saving the fitted pipeline for deployment"],
        practice_exercise="Build a complete preprocessing pipeline: impute, scale numerical, encode categorical, train a model. 1. Is it all inside one Pipeline? 2. Can you save and reload it? 3. Does it pass cross-validation without leakage?",
        quiz=[QuizQuestion(question="What is the correct order for preprocessing?", options=["Scale → Split → Encode → Model", "Split → Impute → Scale/Encode → Model", "Encode → Split → Scale → Model", "Model → Split → Preprocess"], correct_index=1, explanation="Always split first, then preprocess on the training data only. Scaling or encoding before splitting lets the preprocessor see test data — that's data leakage.")],
        takeaways=["Split → Preprocess (fit on train) → Model → Evaluate", "Always use Pipeline and ColumnTransformer", "Document everything and save fitted pipelines"],
        lab_module="preprocessing",
    ),
]
